### ISSUE TITLE
Pending transactions are lost after entering new view

### ISSUE THREAD

**Issue by semuxproject** [semuxproject/semux#1]
* proposal will be dropped after receiving 2/3+ reject votes
* pending manager is not checking if the transactions have been included or not

**Comment by yulongnuco** [comment]
Fixed by 36f3fcec3b0f46a44f4b5ffe11a5e203a70cf6cb

**Comment by semuxproject** [comment]
Fixed by 36f3fcec3b0f46a44f4b5ffe11a5e203a70cf6cb
