### ISSUE TITLE
Incorrect stats, double blocks.

### ISSUE THREAD

**Issue by r1d1-btct** [semuxproject/semux#100]
Hi! My validator is r1d1. 
In the info dialog window I can see: 
25 forged blocks and 7 missed. 
But I have forged 32 blocks. I received 320 SEM for this blocks.
And in the block explorer forged count is 32 and rows count is 32 too. 

![semux_r1d1](https://user-images.githubusercontent.com/32393567/31807693-cea168bc-b599-11e7-896b-708f32c89804.png)

http://semuxchain.info/account/0xe0151bc0ab22cfa559c8c5cd7f10d36f97e7a052

![block_explorer](https://user-images.githubusercontent.com/32393567/31807856-a240809a-b59a-11e7-8ade-c9b14cff38f5.png)

But there same info as in the wallet: http://semuxchain.info/delegates/

![block_explorer2](https://user-images.githubusercontent.com/32393567/31808072-d5b0c240-b59b-11e7-8861-12ab523a419c.png)

Logs, for example. I forged 47123 on the second try and then I forged next block 47124. 
So, I think all validators with missed blocks have double blocks and incorrect forged count. 
Then lower rate (more missed) then more doubled blocks. 
So such validators can forge more blocks per day than another.

 ```
10/19 21:54:16 [cons] INFO SemuxBFT - Entered new_height: height = 47123, # validators = 63
 10/19 21:54:18 [cons] INFO SemuxBFT - Entered propose: height = 47123, view = 0, primary = false, # connected validators = 1 + 22
10/19 21:54:26 [cons] INFO SemuxBFT - Entered validate: proposal = false, votes = [3, 3] [0, 0] [0, 0]
10/19 21:54:34 [cons] INFO SemuxBFT - Entered pre_commit: proposal = false, votes = [3, 55] [0, 8] [0, 0]
10/19 21:54:39 [cons] INFO SemuxBFT - Entered propose: height = 47123, view = 1, primary = true, # connected validators = 1 + 22
10/19 21:54:47 [cons] INFO SemuxBFT - Entered validate: proposal = true, votes = [4, 0] [0, 0] [0, 0]
10/19 21:54:55 [cons] INFO SemuxBFT - Entered pre_commit: proposal = true, votes = [57, 0] [7, 0] [0, 0]
10/19 21:55:03 [cons] INFO SemuxBFT - Entered commit: proposal = true, votes = [58, 0] [56, 0] [5, 0]
10/19 21:55:04 [cons] INFO SemuxBFT - Entered finalize: proposal = true, votes = [58, 0] [56, 0] [42, 0]
10/19 21:55:04 [cons] INFO SemuxBFT - Block [number = 47123, view = 1, hash = aa9c8c051365a18509d7b49ce8dbf04f6a4677f999dedecc6744a4b79cf433f2, # txs = 0, # votes = 56]

10/19 21:55:08 [cons] INFO SemuxBFT - Entered new_height: height = 47124, # validators = 63
10/19 21:55:10 [cons] INFO SemuxBFT - Entered propose: height = 47124, view = 0, primary = true, # connected validators = 1 + 22
10/19 21:55:18 [cons] INFO SemuxBFT - Entered validate: proposal = true, votes = [4, 0] [0, 0] [0, 0]
10/19 21:55:26 [cons] INFO SemuxBFT - Entered pre_commit: proposal = true, votes = [56, 2] [3, 0] [0, 0]
10/19 21:55:34 [cons] INFO SemuxBFT - Entered commit: proposal = true, votes = [56, 2] [56, 0] [3, 0]
10/19 21:55:37 [cons] INFO SemuxBFT - Block [number = 47124, view = 0, hash = 2582f6107861cd38ccc3b1948b36a214ad5b73f7eec9041dfd538992dcf5f2e4, # txs = 0, # votes = 56]
10/19 21:55:37 [cons] INFO SemuxBFT - Entered finalize: proposal = true, votes = [56, 2] [56, 0] [42, 0]
```
Double blocks (47249 - 47250,  47187 - 47186, 47123 - 47124): 

![double_blocks](https://user-images.githubusercontent.com/32393567/31807897-e6c3579c-b59a-11e7-81cf-4e6e810d7894.png)

**Comment by shewscrypto** [comment]
Stats are still incorrect in beta 5. Everyone has been reset to zero forged but kept the (incorrect) amount of missed blocks

![image](https://user-images.githubusercontent.com/32035546/31866654-72e86ec6-b7b5-11e7-9fb3-b13ae89a5cb7.png)
![image](https://user-images.githubusercontent.com/32035546/31866658-7eeb8c44-b7b5-11e7-9509-872f44bf6239.png)

**Comment by semuxproject** [comment]
@shewscrypto you need to re-sync to see the correct stats. Your stats: blocks forged 14, turns hit 11, turns missed 1, rate 91.7%
