### ISSUE TITLE
Delegates view - System delegates (semux1/2/3/4) displays incorrect registration date

### ISSUE THREAD

**Issue by ocvaad** [semuxproject/semux#106]
System delegates semux1/2/3/4 registration date set to 1970-01-01

![image](https://user-images.githubusercontent.com/32023262/31851472-2e48dc20-b66f-11e7-8556-629cf1149b73.png)

**Comment by semuxproject** [comment]
Semux 1-4 are genesis delegate to boot up the network to. Their registration date is the timestamp of genesis block.

TODO: set the timestamp of genesis block

**Comment by semuxproject** [comment]
Fixed
