### ISSUE TITLE
Delegates view - consider expand statistics view - add last 24 hours - etc. 

### ISSUE THREAD

**Issue by ocvaad** [semuxproject/semux#107]
Implemented statistics for delegates is "global". 
Last 24 hours statistics have more usage as performance indication for user.

Since users should place vote for delegates, should consider to add to statistics something like:
"Total earnings"
"Last 24 hours earnings" 
"My total earnings"
"My last 24 hours earnings"

**Comment by semuxproject** [comment]
Redundant, see #107
