### ISSUE TITLE
Delegates view - make Delegate name editable

### ISSUE THREAD

**Issue by ocvaad** [semuxproject/semux#108]
There are 2 different ideas that should be considered: 

1. As a delegate user I should be able to override display name of the my delegate - and it should be updated on all the wallets.
For example I'd like to update delegate name with hardware config it is runs on. 

2. As a regular user of the wallet app, I'd like to be able to set custom name for the delegates, and be able to set view back to the delegate original name.  
On user level custom delegate names should relevant for the local wallet only. 

![image](https://user-images.githubusercontent.com/32023262/31852879-708d0aa2-b688-11e7-9c8f-ff99fa092ba1.png)

**Comment by semuxproject** [comment]
Editing delegate names is not recommended, but adding label for address (including delegate) would be a nice feature to have.
