### ISSUE TITLE
Delegate mode - add view for "Active Voters"

### ISSUE THREAD

**Issue by ocvaad** [semuxproject/semux#109]
As a delegate I'd like to be able to view all the users that voted for me. 
Voters view should display statistics like: 

1. Registered date. 
2. Wallet address from where the vote was made. 
3. Amount of votes. 
4. Unpaid balance. 
5. Paid balance. 
6. Total income (relevant for this voter). 

Feel free to rework this item to anything more useful.

**Comment by semuxproject** [comment]
The GET_VOTES feature has been implemented in the latest kernel. Display the list of voter in the Delegate Dialog could be implemented.

**Comment by semuxproject** [comment]
Delegate details dialog has been implemented
