### ISSUE TITLE
Incorrect Java version checking

### ISSUE THREAD

**Issue by kazanzhy** [semuxproject/semux#110]
My system:
OS: Ubuntu 16.04.3
Java version: "9.0.1"

I downloaded 'semux-1.0.0-beta.4.tar.gz', run .sh script and get "Error: Java 8 or above is required".

Error in this pipe of script:
java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f2
(java version "9.0.1")                | 9.0.1          |  0

Correct line:
java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f1

**Comment by semuxproject** [comment]
Java 8: `1.8.0_131`
Java 9: `9.0.1`

Our script needs to deal both version

**Comment by mdodong** [comment]
this seems to work but doesn't look right, I don't really have much experience with bash but I can read some :smiley: 
```

#!/bin/sh
version=$(java -version 2>&1 | grep -i version | cut -d'"' -f2 | cut -d'.' -f1-2)
version2=$(echo "scale=2;$version*100" |bc)
version3=${version2%.*}
if [ $version3 -lt "180" ]; then
    echo "Error: Java 8 or above is required"
    exit 1
fi
```
