### ISSUE TITLE
Regular user mode- add "My Delegates" view 

### ISSUE THREAD

**Issue by ocvaad** [semuxproject/semux#111]
As a regular user that votes for delegates I should be able to view relevant delegates only. 
For example - I voted for 3 delegates out of active 50, and I'd like to view only delegates that I voted for. 
On this view I'd like to see the following:

1. My address from where I voted. 
2. Amount of my votes. 
3. Delegate address where vote was applied. 
4. Delegate reward for voting. 
5. Delegate status (online/offline)

Feel free to rework this item to anything more useful.

**Comment by semuxproject** [comment]
For now, the work around is by sorting the table (click the table header)

In the future: add a button on the right panel, switching between `All delegates` and `Voted delegates`
