### ISSUE TITLE
Unable to unvote with low balance

### ISSUE THREAD

**Issue by phash** [semuxproject/semux#112]
You are unable to unvote if your current balance is below the necessary transaction fee.

Suggestions:
1: Pay the transaction fee on vote (double on vote, none on unvote)
2: Pay the transaction fee with your locked balance

**Comment by lodyman93** [comment]
1: Pay the transaction fee on vote (double on vote, none on unvote)
Will make the fees larger than normal if you voted twice for the same delegate then unvoted all at once

i'd say another field to be created to hold a defined amount (say 10 uSim) at any given time and not spendable only to be used in tx fees and is deducted when you receive any coins or when you vote for the first time

paying anything with locked balance can be dangerous

**Comment by clip123** [comment]
Hold SEM due to your votes may not be ideal in my opinion. Best approach may be to deduct the fees directly from the SEMs received by un-voting. This way, we can un-vote multiple time without having to hold anyone's SEMs.

**Comment by semuxproject** [comment]
@phash is working on adding warnings for this condition

**Comment by semuxproject** [comment]
Has been patched by recent commits.
