### ISSUE TITLE
can't sent transactions by default comma

### ISSUE THREAD

**Issue by extens1s** [semuxproject/semux#120]
By default, a comma is set in the transaction commission.
But with it payment is not sent and from the wallet should not be any reaction.
To send a payment, you need to change the comma to the dot

![screenshot_5](https://user-images.githubusercontent.com/33003672/31863810-bf2df918-b75b-11e7-9fe4-9cd740510c69.png)
.

Not a critical bug, but still.

**Comment by semuxproject** [comment]
Should be fixed by 7aa0799eddf19bf7e62bead8fe8e000a0542bd0e
