### ISSUE TITLE
Can't vote because of space as a thousands separator

### ISSUE THREAD

**Issue by ilya-stepanov** [semuxproject/semux#121]
Can't vote with more than 999 SEM because if there is bigger amount the space appear as a thousands separator. As a result I have error (see screenshot).

https://image.prntscr.com/image/rJ5P6-ROSYOzHQ9ZqrJPCQ.png

**Comment by phash** [comment]
does it appear while you type in?

**Comment by ilya-stepanov** [comment]
Yes, it was.
It's fixed in the new version as I can see.

**Comment by semuxproject** [comment]
Should be fixed by 7aa0799eddf19bf7e62bead8fe8e000a0542bd0e
