### ISSUE TITLE
RPC get_block does not contain coinbase transactions.

### ISSUE THREAD

**Issue by Messier81z** [semuxproject/semux#124]
Get_block returns result that does not contain the coinbase transaction in the "transactions" field.

I.e.

{
  "result": {
    "date": "2017-10-01 22:10:29",
    "number": 5000,
    "view": 0,
    "coinbase": "0x070811dbe362bdec3e7fd7ecf96aa3f194989158",
    "data": "0x",
    "prevHash": "0x7ec11dda712732e78c701e4a3118ece7f705a2ab3d65269b646979ca624cbbf1",
    "transactionsRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "stateRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "transactions": [], **<-- <MISSING COINBASE TX ID>**
    "hash": "0xb6efa42cc5854b855014eb3a04dd972194ae0b43fe6238e15032f9172ccd0142",
    "timestamp": 1506892229263,
    "resultsRoot": "0x0000000000000000000000000000000000000000000000000000000000000000"
  },
  "success": true
}

**Comment by semuxproject** [comment]
Coinbase transactions are internal structure
