### ISSUE TITLE
not sync

### ISSUE THREAD

**Issue by ashipka11** [semuxproject/semux#13]
delete previous
delete database folder 
v 1.0.3
09/12 19:17:39 [main] INFO Config - Latest block number = 0
09/12 19:17:40 [main] INFO NodeManager - Node manager started
09/12 19:17:40 [cons] INFO SemuxBFT - Consensus started
09/12 19:17:40 [p2p] INFO PeerServer - Starting peer server: address = 0.0.0.0:5
161
09/12 19:17:40 [cons] INFO SemuxBFT - Entered new_height: height = 1, # validato
rs = 4

**Comment by semuxproject** [comment]
@ashipka11 We just upgraded our testnet and wallet. Please download and try again

**Comment by semuxproject** [comment]
Note: to be able to sync, one needs to set the computer date/time correctly.
