### ISSUE TITLE
Localization, InsufficientFunds

### ISSUE THREAD

**Issue by r1d1-btct** [semuxproject/semux#135]
Localized message with key 'InsufficientFunds' has {0} for amount and it used in the SendPanel and DelegatesPanel. 

1. There are no problem with DelegatesPanel: 
```
} else if (a.getBalance() < Config.DELEGATE_BURN_AMOUNT + Config.MIN_TRANSACTION_FEE_SOFT) {
                JOptionPane.showMessageDialog(this, MessagesUtil.get("InsufficientFunds",
                        SwingUtil.formatValue(Config.DELEGATE_BURN_AMOUNT + Config.MIN_TRANSACTION_FEE_SOFT)));
```

2. But in the SendPanel there are no amount: 
  ```
              } else if (value + fee > acc.getBalance()) {
                    JOptionPane.showMessageDialog(this, MessagesUtil.get("InsufficientFunds"));
```

As result: 

![insufficientfunds](https://user-images.githubusercontent.com/32393567/31957723-dc9bbf34-b919-11e7-876b-6ebc14ea2fd6.png)

And more important the localized message is incorrect.

When translated in English it like 'Insufficient funds! You need {0}.' This is good for delegates where amount is fixed and it doesn't fit for SEM sending where you should get to know maximum available amount minus fee. 

I suggest using two different messages one for the DelegatesPanel, the second for the SendPanel and add maximum available amount (without fee) as argument for a message in the SendPanel.

**Comment by testzcrypto** [comment]
Please check the last version which already in GitHub: https://github.com/semuxproject/semux/blob/master/src/main/java/org/semux/gui/panel/SendPanel.java#L232

**Comment by semuxproject** [comment]
This should have been fixed by recent commits
