### ISSUE TITLE
Unable to register as Delegate

### ISSUE THREAD

**Issue by ocvaad** [semuxproject/semux#145]
Bug found by **honeycrypto**
User cannot register as Delegate. 
Wallet displays regular Transaction Sent message, but money amount doesn't reduced from the wallet and 
wallet still not registered as Delegate. 

wallet sends DELEGATE transaction with 0.005 fee
while you increased default minimum transaction fee to 0.05 everywhere, so no one wants to include DELEGATE txs to the block

**Comment by phash** [comment]
can't register, too

**Comment by phash** [comment]
worked after some time.. straneg

**Comment by semuxproject** [comment]
Fixed
