### ISSUE TITLE
Cloning "Hello, World"

### ISSUE THREAD

**Issue by r1d1-btct** [semuxproject/semux#148]
I think it's not safe to use only peer & timestamp in the 'hello' message without check the ip from peer field of the message or without another verification method.
We can copy HelloMessage from validator when it's start after client update (for example) and resend to other peers.
1. Those peers that will receive the message from us first, they will send DUPLICATE_PEER_ID to real validator and this validator will not be able to connect with these peers. 
If validator will be shutdowned in less then 1-2 minutes (NET_HANDSHAKE_EXPIRE = 5 * 60 * 1000 - time to close active connections on the peer side) after we will receive HelloMessage from him, I think we can connect with all active peers and such validator cann't connect to network again cause DUPLICATE_PEER_ID. But the probability of this is small - there is a very short time span.
2. We can duplicate such messages from different validators and maybe we can receive 2/3 positions in someone active validators list and provoke try to sinc when his turn comes to propose the block and he will miss it.
3. Maybe something else.

I don't test it. Maybe it's not working or not danger.

HelloMessage: 
```
SimpleEncoder enc = new SimpleEncoder();
enc.writeBytes(peer.toBytes());
enc.writeLong(timestamp);
this.dataToSign = enc.toBytes();
this.signature = coinbase.sign(dataToSign);
```

SemuxP2pHandler:
```
ReasonCode error = null;
if (!isSupported(peer.getP2pVersion())) {
    error = ReasonCode.BAD_PROTOCOL;
} else if (client.getPeerId().equals(peer.getPeerId()) ||
        channelMgr.isActivePeer(peer.getPeerId())) {
    error = ReasonCode.DUPLICATE_PEER_ID;
} else if (chain.getValidators().contains(peer.getPeerId())
        && channelMgr.isActiveIP(channel.getRemoteIp())) {
    error = ReasonCode.SLOW_PEER;
} else if (!helloMsg.isValid()) {
    error = ReasonCode.INVALID_HANDSHAKE;
}
```

**Comment by semuxproject** [comment]
Agreed. This is not secured enough.

``sign(peer, timestamp)`` should be ``sign(peer, id_peer_to_connect)``

**Comment by semuxproject** [comment]
Fixed by adding IP verification
