### ISSUE TITLE
Wallet balances BUG ?

### ISSUE THREAD

**Issue by busminer** [semuxproject/semux#149]
Wallet balances BUG ?
My wallet adress [quote]0xf66d38d83460b065a50def2a7ff78d774c95a2a9[/quote]
https://semux.info/explorer/account/0xf66d38d83460b065a50def2a7ff78d774c95a2a9
I have voted for 5 delegates 1654 each, in new pool.
http://picua.org/img/2017-10/26/i9ejxol7vymb9wpem9s1h0opz.png
But wallet steel shows that i have 2935 SEM and blockexplorer shows correct balance.
http://picua.org/img/2017-10/26/ylryuqwzjdagyz5b24yg8bfq2.png
img]http://picua.org/img/2017-10/26/mpg3f5dwtxcfm3pq3wfrhjk6q.png
http://picua.org/img/2017-10/26/i7vyx8e41jy47ir0n424kupc8.png

**Comment by r1d1-btct** [comment]
You have 2,935 SEM, not 2935. 
This comma also confuses me in the my wallet. I preffer a point. But there are no choice except change OS locale settings.

I think better way is to use a point by default in the wallet like in others wallets.

**Comment by semuxproject** [comment]
Number are formatted based on system locale settings. Will consider display all number as XXX.XX if it's strongly needed.
