### ISSUE TITLE
API allows too many functions

### ISSUE THREAD

**Issue by Dariloff** [semuxproject/semux#151]
I can check all peers for open api to port 5171. If i find it, i can request "block_ip", "add_node" and other not closed by password methods. If user forget to set password, i can check it by url "/list_accounts?password=", then request "delegate/vote/unvote" and "create_account" methods. Also, i can make ddos peer, if it's competitive validator by request highly demanding method.

I think, api should be closed for external ip by default or create api_key.

**Comment by semuxproject** [comment]
API is not enabled by default. The current password authentication is very naive. Will implemented HMAC https://en.wikipedia.org/wiki/Hash-based_message_authentication_code

**Comment by semuxproject** [comment]
We decided to implement basic authentication instead of HMAC. Further encryption should be done at transport level.
