### ISSUE TITLE
Missed blocks

### ISSUE THREAD

**Issue by r1d1-btct** [semuxproject/semux#154]
I wrote already about big amount of missed blocks. To many blocks are missed (if my count is correct missed rate is about 25-35%). 
In one day I missed 7 blocks, then I connect through tor and then I missed about 1 block per day. I think the increased latency played a role.
I suppose some blocks missed cause part of validators did not moved to a new height yet and when they received our proposal they reject it because they have previous height.
Today I edit the source and run with next changes: 
1) add delay 1 sec before broadcasting the proposal;
2) reduce netx stage timeout Config.BFT_VALIDATE_TIMEOUT to same 1 sec. 

Now is ok, but else under the tor. 
I think it makes sense. Maybe without tor time should be 2 sec, I don't know, need tests.

How do you think may this help?

-----------------------------------------
Average block time for last 24 hour is 41 sec. Maybe if we add bigger timeouts (say to 45 or 60 sec) and add timeout before proposal broadcasting we will not lose so many blocks?

**Comment by semuxproject** [comment]
`BFT_NEW_HEIGHT_TIMEOUT` serves the purpose of delaying block proposal and waiting for other peers to enter the new height. It's currently set to 2 seconds and may be tweaked as we see appropriate.

**Comment by r1d1-btct** [comment]
From my tests:
1. Increasing timeout is not valuable as I expected. It's give me only several additional votes (2-3 in avg).
Typical example: 
```
10/30 13:44:07 [cons] INFO SemuxBFT - Entered new_height: height = 71647, # validators = 86, primary = lemon, #8
10/30 13:44:07 [Thread-20] INFO SemuxBFT - Heights = {71645=22, 71646=57}
10/30 13:44:08 [Thread-20] INFO SemuxBFT - Heights = {71645=13, 71646=66}
10/30 13:44:09 [Thread-20] INFO SemuxBFT - Heights = {71645=11, 71646=68} <- Default timeout
10/30 13:44:10 [Thread-20] INFO SemuxBFT - Heights = {71645=9, 71646=70} <- +1 sec
10/30 13:44:11 [Thread-20] INFO SemuxBFT - Heights = {71645=7, 71646=72} <- +2 sec
```

2. I think more important is open 5161 port, which allows to maintain a connection with a large number of participants. 
Closed port: 20 validators.
Open port: 77 validators.

**Comment by semuxproject** [comment]
We increased the `PROPOSE` state timeout. Let's see how things go.
