### ISSUE TITLE
Small transactions reported as Zero

### ISSUE THREAD

**Issue by finbarrmccarthy** [semuxproject/semux#159]
When sending a small transaction eg >=0.0005 the transaction gets reported in the UI az zero.

![image](https://user-images.githubusercontent.com/4437417/32147963-7ea1f106-bce7-11e7-8f72-17e3880210db.png)

https://semux.info/explorer/transaction/0x1915334a0673d8553d991835eee168ed2ba6d77b30f84dcbde775c506632e3f6

![image](https://user-images.githubusercontent.com/4437417/32147987-d4759376-bce7-11e7-8a9b-6f9c1d84474e.png)

Similarly, if the transaction is between 0.0005 and it gets rounded up to 0.001

I am not sure if this is by design and perhaps nobody will be sending such small transactions.

**Comment by phash** [comment]
maybe it would be better to show all decimals?

**Comment by finbarrmccarthy** [comment]
Within reason, I would think.

**Comment by finbarrmccarthy** [comment]
How many decimals are in SEM?

**Comment by semuxproject** [comment]
There are 9 decimals. From rc1, only the leading 2 decimals will be displayed.

**Comment by finbarrmccarthy** [comment]
I think looking at other wallets 2 decimals for balance seems like default, but on transactions, if it is possible to send small amounts I think it should be displayed in the transactions screen. Either that or change the coin to only have 2 decimal places (or possibly limit sending small amounts), but if it became very valuable that might be a problem.

**Comment by semuxproject** [comment]
We can always upgrade the wallet to show more digits if necessary, and this won't affect consensus.

**Comment by finbarrmccarthy** [comment]
Fair enough.
