### ISSUE TITLE
Inter account transfers not working as expected

### ISSUE THREAD

**Issue by finbarrmccarthy** [semuxproject/semux#162]
When I create a new receive address it can independently hold funds. When I try to send funds from Account 0 to Account 1 the the UI reports success but the transaction never appears to occur. When I retry the transaction in the same direction I get transaction failed.

![image](https://user-images.githubusercontent.com/4437417/32148515-36bf9542-bcf0-11e7-94be-d8c483386155.png)
The first time I get a confirmation saying it might take 20 seconds.... etc, but nothing happens

The second time I get a transaction failed.
![image](https://user-images.githubusercontent.com/4437417/32148518-42b748cc-bcf0-11e7-85cc-561a278876f4.png)

Inter-account transfers from Account 1 => Account 0 appear to work consistently

**Comment by semuxproject** [comment]
Needs confirmation!

**Comment by semuxproject** [comment]
Unable to re-produce this problem.
