### ISSUE TITLE
Not sure who I am voting for

### ISSUE THREAD

**Issue by clip123** [semuxproject/semux#171]
Clicked on beta to vote after voting for alpha and even inputted name in the delegate field. But vote went to alpha and not beta delegate.

**Comment by mdodong** [comment]
You don't have to put anything on the delegates field unless you are registering for a delegate. If the vote did not went to the intended delegate you can always unvote and vote again.

**Comment by clip123** [comment]
yea i can do that. a confirmation window showing showing who I am voting for would be nice ad-on...

**Comment by semuxproject** [comment]
<img width="405" alt="a" src="https://user-images.githubusercontent.com/30612819/33173620-cbeb3f46-d022-11e7-88d4-e9d46df4556e.png">

**Comment by cryptokat** [comment]
I am on this
