### ISSUE TITLE
Votes for delegates are processed in sequential process

### ISSUE THREAD

**Issue by clip123** [semuxproject/semux#174]
If I have 100 votes and I do 50 votes for delegate A and 50 votes for delegate B before the blocks are forged. Then votes for A get processed first and then in next block votes for B get processed.

I have seen few times that multiple votes by the same person are not processed in the same block.

**Comment by semuxproject** [comment]
It's up to the validator to decided which transaction get included in the current block.

**Comment by clip123** [comment]
Thanks, I will close the issue then.
