### ISSUE TITLE
RC1 Release not working with PIA VPN

### ISSUE THREAD

**Issue by shewscrypto** [semuxproject/semux#182]
When I try run the RC1 with PIA running it stops without throwing and error. This is all I get
![image](https://user-images.githubusercontent.com/32035546/32440496-608a369a-c32e-11e7-9a64-d8a552a240dd.png)

Turn off VPN and bingo, everything works

**Comment by semuxproject** [comment]
See #190

**Comment by shewscrypto** [comment]
I am still having this issue in latest RC2 release. When I have the vpn running it will not sync, when I turn it off it syncs. May need to reopen this bug, as it wasn't there on alpha or beta releases
