### ISSUE TITLE
can't login again at version semux-1.0.0-rc.1

### ISSUE THREAD

**Issue by kaitoukidd** [semuxproject/semux#189]
error is here:
 [main] ERROR Wallet - Failed to decrypt the wallet data

![image](https://user-images.githubusercontent.com/8613602/32469876-09b0740a-c398-11e7-9e92-4e6e60c8b229.png)

i downloaded rc version and  run it at 11/6. login and vote and etc are normal.
but when i login again today(UTC 11/6 23:35),i can't login.
my address is  0xd024f1ff53b26686044349ec0384679fe4131eeb
you can check the block explorer and confirm my actions.

**Comment by semuxproject** [comment]
You may have entered incorrect password
