### ISSUE TITLE
error translation

### ISSUE THREAD

**Issue by jay877** [semuxproject/semux#192]
In the tab "Main" in the rus version of wallet the Available balance is not translated to rus, should be "Доступно"

**Comment by testzcrypto** [comment]
Fixed in l10n update https://github.com/semuxproject/semux/pull/193

**Comment by jay877** [comment]
Update as of November 1, I downloaded the latest version of the wallet November 6, this bug is now, I can attach a screenshot

**Comment by testzcrypto** [comment]
I just update it today (https://github.com/semuxproject/semux/pull/193) this fix not merged yet, you should wait next release.

**Comment by semuxproject** [comment]
Should be fixed in next release
