### ISSUE TITLE
Behavior of Swing GUI Popup is screwed

### ISSUE THREAD

**Issue by phash** [semuxproject/semux#203]
The Popup mechanics are screwed up. Swing fail! (not semux, just swing)

go to: delegates -> table -> double click -> new DelegatesDialog

1. without marking or clicking anything first
- right click on address -> copy
- try to copy it to a texteditor: empty!

2. left click the thing you want to copy
- left click 
- copy 
- nothing

3. left click and mark what you want to copy:
- left click address 
- mark address 
- right click on address 
- you get the address

4. left click and mark but click somewhere else
- left click address
- mark address 
- right click somewhere
- you get the address

5. consider having different JPopUp Menus
- on name you have copy
- on address you have insert to sendPanel
-- left click name
-- mark name
-- right click address
-- select "insert to SendPanel"
-- value sent to SendPanel is now Name and not address - even though name does not have a  insert to SendPanel PopupItem

**Comment by semuxproject** [comment]
We're moving towards JavaFX. Hopefully, some of the issues can be addressed.
