### ISSUE TITLE
(re)start Option with given password

### ISSUE THREAD

**Issue by phash** [semuxproject/semux#214]
add a start option to enter password for default wallet on startup
add "restart on fail"

**Comment by cryptokat** [comment]
Hi, I am not sure what you mean exactly. Could you please elaborate the idea behind this feature?

**Comment by phash** [comment]
I can start my wallet from a cli interface and automatically sign in to my wallet with cli options
I can check with a script whether my wallet is still running and restart it, if it is crashed

**Comment by phash** [comment]
already implemented
