### ISSUE TITLE
Wallet security enhancements

### ISSUE THREAD

**Issue by ocvaad** [semuxproject/semux#220]
Actions that can affect wallet balance or wallet.dat file should be password protected to ensure that wallet is used by owner only. 
In case of security breach to validator pc or to user pc, hacker can freely transfer balances/vote/unvote. 
In current implementation password protection used only to load client and that leaves client in "Unlocked mode" untill user invoke "Lock" state. 

Should consider review API commands that might affect balances or votes for the same security issue.

**Comment by semuxproject** [comment]
Needs enhancement on this, as people can export private key even in the "locked" mode.

**Comment by cryptokat** [comment]
Would it be more secure to keep the wallet always locked?
Even if we add a password prompt for each sensitive operation, the unlocked wallet data structure will still live in the JVM runtime.

**Comment by finbarrmccarthy** [comment]
Another way to think about this might be to use the Validator wallet as a "Hot Wallet". In this scenario, the validator could nominate (possibly through config) an address (Cold Wallet) where to send block rewards. And if there was some compromise on the Validator the worst effect might be to divert the rewards until the owner noticed the rewards were not incoming.

this might make Validators less of a Target.

The suggested password measures are good too - but this might be another layer.
