### ISSUE TITLE
Multiple Wallets Support

### ISSUE THREAD

**Issue by clip123** [semuxproject/semux#224]
Is it possible to have multiple wallets and consolidated total SEMs? For example:
Wallet 1: 100 SEMs
Wallet 2: 200 SEMs
**Total: 300 SEMs**

**Comment by semuxproject** [comment]
Since multiple account in one wallet is already supported, I didn't see a strong requirement for multiple wallets.

**Comment by clip123** [comment]
Thanks, I will close this until the time a need arises for multiple wallets support.
