### ISSUE TITLE
What's my private key?

### ISSUE THREAD

**Issue by clip123** [semuxproject/semux#226]
Anyway to export private key in plain text and please add import option to import private key

**Comment by cryptokat** [comment]
@clip123 You can use the `--cli --dumpprivatekey [address]` feature on develop branch https://github.com/semuxproject/semux/tree/develop

**Comment by clip123** [comment]
Hi, can it be done from the interface/app?

**Comment by cryptokat** [comment]
@clip123 Sorry there isn't a place where you can export/import private key from UI for now. The feature might be added soon in the future release.

**Comment by semuxproject** [comment]
Implemented
