### ISSUE TITLE
CLI: Add --getbalance [address]

### ISSUE THREAD

**Issue by cryptokat** [semuxproject/semux#227]
- [ ] if address is empty, prints the aggregated balance of whole wallet file
- [ ] if address is non-empty, prints the balance of the address

**Comment by cryptokat** [comment]
the implementation might end up with an API client

**Comment by semuxproject** [comment]
Maybe we should attach a console to the CLI. The console interpret the commands dynamically.

**Comment by cryptokat** [comment]
@semuxproject agree
It would be a better approach to decouple the API client like Ethereum does. [Web3J](https://docs.web3j.io/command_line.html) can be a good reference.

### Links
- https://github.com/web3j/web3j
- https://docs.web3j.io/command_line.html
- https://github.com/ethereum/web3.js/

**Comment by semuxproject** [comment]
RESTful API should be used for this purpose
