### ISSUE TITLE
Add git style guide

### ISSUE THREAD

**Issue by semuxproject** [semuxproject/semux#232]
As our community grows, it's necessary to add a Git style guide for better collaboration.

https://github.com/agis/git-style-guide

**Comment by cryptokat** [comment]
Ethereum is using https://gitcop.com/ for automated commit message style checking.

![selection_406](https://user-images.githubusercontent.com/32390172/32765033-9545ccda-c943-11e7-8d15-1c819821321a.png)

**Comment by semuxproject** [comment]
A new [contributing guide](https://github.com/semuxproject/semux/blob/master/.github/contributing.md) has been added.

Not sure if we should enforce the commit message check.
