### ISSUE TITLE
OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by semuxproject** [semuxproject/semux#249]
This happened on my Macbook pro when switching from `-Xmx8g` to  `-Xmx4g`. 

```
Exception in thread "cons" java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by ocvaad** [comment]
same exception here, 
WinX64 VPS with start command set to:  java -cp "./config;./lib/*" org.semux.Semux %*

**Comment by semuxproject** [comment]
Trying to reproduce this issue with the following setup:
1. Four local nodes on dev net
2. One client keeps pushing transactions

<img width="867" alt="1" src="https://user-images.githubusercontent.com/30612819/32998385-a29f6dea-cd68-11e7-90e0-5e20db8aab2b.png">
<img width="861" alt="2" src="https://user-images.githubusercontent.com/30612819/32998386-a2ea23d0-cd68-11e7-9211-fcb52903c2b3.png">
<img width="862" alt="3" src="https://user-images.githubusercontent.com/30612819/32998387-a334d39e-cd68-11e7-8232-8c234e4ecd15.png">

**Comment by semuxproject** [comment]
Heap dump analysis

<img width="819" alt="dump" src="https://user-images.githubusercontent.com/30612819/33001127-f812d792-cd79-11e7-8294-670672d71500.png">

**Comment by semuxproject** [comment]
Memory usage has been optimized
* Core: 71c22a6d7bde33d58feaeaf5ac87922e05bf3d04
* Consensus: cc8c35f8682e5eba21c8147c345ff2203f5596f4
* Net: d4916d7cac04aeb5e9e0ed8c3e2fa49ff99a1139

**Comment by phash** [comment]
I am running a node on my linux laptop. 8 GB Ram - xmx 4G
this is quite stable (i had to declare -xmx 4g - without this it kept crashing)

would it be possible to pack in a maximum amount of transactions to one block? (maybe the validator can tell, how many TX he can handle. If it fails, it reduces the amount for the next block. If it succeeds it increases its amount?)
