### ISSUE TITLE
Do not open the wallet semux.bat

### ISSUE THREAD

**Issue by BoLODbKA** [semuxproject/semux#257]
![345](https://user-images.githubusercontent.com/33674617/33028778-d3c093d0-ce27-11e7-97ca-cb54aa673fb3.png)
Do not open the wallet semux.bat.
I use laptop samsung winds 8 '64, I also try on another noutube cube asus windows 10' 64. Same problem.
 First a window with a password flies, I enter the password and everything disappears.
 After entering a new password, the file does not open.
The cash register was able to run only through the command line (cdm).

For verification, I can provide access to the Web browser. (TeamViewer)
![3](https://user-images.githubusercontent.com/33674617/33028766-cedd757c-ce27-11e7-92e7-4f0fd085ea45.png)

**Comment by clip123** [comment]
I think this can be address by this issue#225
https://github.com/semuxproject/semux/issues/225

**Comment by BoLODbKA** [comment]
"I think this can be address by this issue#225"  there is no other.

**Comment by mdodong** [comment]
update to RC3
