### ISSUE TITLE
Remove Delegate Registration Panel from registered delegates

### ISSUE THREAD

**Issue by finbarrmccarthy** [semuxproject/semux#263]
Perhaps this is getting into the minutiae, but, I cant think of any practical purpose to leave the Delegate Registration Panel visible once the client wallet has been registered as a delegate.

Would it be better to run a check and hide if already a delegate?

**Comment by phash** [comment]
maybe you want to register more delegates?

**Comment by finbarrmccarthy** [comment]
I thought 1 delegate per wallet on a running instance? Clearly if I switch wallet.data and the new wallet is not a delegate then display the panel again (unless I am misunderstanding how it works).

**Comment by semuxproject** [comment]
This delegate panel is useful for multi-account management. Now preliminary checks are added before registering a delegate.
