### ISSUE TITLE
I lose the status "delegate" if I use the export / import of a private key

### ISSUE THREAD

**Issue by telllic** [semuxproject/semux#265]
Semux v1.0.0-rc.3

1. I have the status of delegate
2. I export my private key, delete the file "wallet.data", create a new file "wallet.data"and import the private key. Now I do not have the status "delegate".
![2017-11-24_12-20-29](https://user-images.githubusercontent.com/32963217/33201441-f7db0182-d111-11e7-87bd-7e0b9f3858c2.png)

**Comment by mdodong** [comment]
make sure when you start the wallet the default coinbase( account#0) is the delegate account.

**Comment by telllic** [comment]
@mdodong I make sure of this ))
