### ISSUE TITLE
Incorrect ip address

### ISSUE THREAD

**Issue by telllic** [semuxproject/semux#266]
![2017-11-24_12-26-44](https://user-images.githubusercontent.com/32963217/33201726-2bbae7d2-d113-11e7-8497-23ecaa919169.png)

**Comment by telllic** [comment]
![2017-11-24_12-36-24](https://user-images.githubusercontent.com/32963217/33202010-39f69ed0-d114-11e7-877c-77b99633c288.png)

**Comment by cryptokat** [comment]
Hi @telllic 
Could you check your IP on https://api.semux.org/ip to see if it's the same as the reported one in your debug.log?

**Comment by telllic** [comment]
![2017-11-24_13-17-14](https://user-images.githubusercontent.com/32963217/33203558-e51b89c4-d119-11e7-9744-a63b6698f88d.png)

**Comment by cryptokat** [comment]
@telllic The behaviour is expected as the program retrieves your public IP from https://api.semux.org/ip

**Comment by telllic** [comment]
![2017-11-24_15-59-12](https://user-images.githubusercontent.com/32963217/33209685-7c442e62-d130-11e7-8b5c-3941fd9552e8.png)

**Comment by semuxproject** [comment]
I will look into this. We were originally using ipify but got some bug reports.

**Comment by telllic** [comment]
Is it possible to specify an IP address in config-file?
