### ISSUE TITLE
API transactions not working

### ISSUE THREAD

**Issue by mdodong** [semuxproject/semux#267]
#### System information

Semux version: `./semux.sh --cli --version`

OS & Version: Linux Ubuntu 16.04

#### Expected behaviour
API
`curl -u user:pass http://127.0.0.1:5171/transfer?from=0x2441fc9610c07b08b4570869a03bf0bc2145be65&to=0x2441fc9610c07b08b4570869a03bf0bc2145be65&value=1000000000&fee=500000`

{"success":true,"hash"..... }
#### Actual behaviour

{"success":false,"message":"Invalid parameters"}
#### Steps to reproduce the behaviour
Enable api
Run api command on terminal using curl or via browser

**Comment by mdodong** [comment]
The same with error on api commands
`vote, unvote and delegate`

**Comment by cryptokat** [comment]
I am unable to reproduce the issue.

According to the error message, the error seems to be caused by parameter validation:
https://github.com/semuxproject/semux/blob/master/src/main/java/org/semux/api/ApiHandlerImpl.java#L344

**Comment by mdodong** [comment]
That's the problem. If you read the API manual I got all the needed parameters to initiate a transaction but still returns an invalid parameter error. The same command works on previous versions. 

We're you able to do a successful transaction using the API?

**Comment by cryptokat** [comment]
Yup I just made a transaction through API successfully.

The command I executed:
```
curl http://user:pass@127.0.0.1:5171/transfer\?from\=0xe77669fc1a8bf22a952b4c61eaad301b502f7dbc\&to\=0xe77669fc1a8bf22a952b4c61eaad301b502f7dbc\&value\=1\&fee\=50000000
``` 

You can check the transaction here:
http://semuxchain.info/transaction/0x602ce4afcf9016d3f652a545bc3ac6d0e9740e2fc3a2d2d8950e5233a9f82246

![selection_413](https://user-images.githubusercontent.com/32390172/33233939-5dee71e6-d259-11e7-9afc-268720100b23.png)

**Comment by mdodong** [comment]
I did another test. This time using a simpler API password and it worked. 

`curl -u 'user':'pass' 'http://127.0.0.1:5171/transfer?from=0x2441fc9610c07b08b4570869a03bf0bc2145be65&to=0x2441fc9610c07b08b4570869a03bf0bc2145be65&value=10000000&fee=50000000'`

`{"result":"0x0cf2ebada8fce036b56ea54430a6b5b49a7ab56875f5481e8e841f08c6cfbe10","success":true}`

Please close this ticket.
