### ISSUE TITLE
Debug Logging - enhancement/configuration

### ISSUE THREAD

**Issue by ocvaad** [semuxproject/semux#274]
In current implementation log written to the single file. 
Should consider the following:

1. Configurable debug log size on UI or via config file. 
   1.1. First approach is to have one file with fixed size. 
    1.2 . Second approach is rename to *.old/ *.old1 /*.old2 etc.  log file once it gets to the maximum size 
     and start new log. 

2. Should consider implementation of different 'levels' for the debug output:
like: 
2.1. Basic - only critical messages + very basic connections info 
2.2. Advanced - critical messages + advanced connections info
2.3. Full - full console output to the log file. 

3. Should consider to extract messages with critical importance to separated log file.

**Comment by cryptokat** [comment]
We may like to make the log rotating feature optional because some Linux users will prefer using the system-wide `logrotate`

**Comment by cryptokat** [comment]
1st and 2nd points are addressed in #279

**Comment by cryptokat** [comment]
@ocvaad addressed in #283
