### ISSUE TITLE
Implement network blacklist and whitelist

### ISSUE THREAD

**Issue by semuxproject** [semuxproject/semux#282]
We need probably implement the IP blacklist and whitelist mechanism for potential DDoS attack, especially for validators.

One option would be adding two files, `whitelist` and `blacklist`, in the config folder in plain text format, so people update the list. The kernel will maintain an IP database in memory for fast querying, with serializing/deserializing supported.

API, and CLI potentially, needs to be enhanced to allow dynamic adding/removing IP entries.

Also, we need consider making connection policy configurable.

**Comment by cryptokat** [comment]
I am looking into this.

Netty's [IP filter package](https://netty.io/4.1/api/io/netty/handler/ipfilter/package-summary.html) will be useful for the implementation.

**Comment by wg135** [comment]
I am not sure malicious IP whitelist and blacklist can help a lot. You can always use crafted IP address when you want to do attacks

**Comment by cryptokat** [comment]
This is already implemented in the latest release.
