### ISSUE TITLE
Wallet backup

### ISSUE THREAD

**Issue by MorgUK** [semuxproject/semux#29]
Win 7 64bit.

When clicking 'backup wallet' you would expect an explorer window allowing me to select a file and enter filename, it instead wants me to select a folder and 'open' it. If you click open it instead saves the wallet in that folder and doesn't allow you to rename before saving.

![semux-issue](https://user-images.githubusercontent.com/11564157/30763743-986ca556-9fdf-11e7-9e57-44054462136d.jpg)

If useful, please donate to delegate address morguk :)

**Comment by semuxproject** [comment]
Fixed. Will be included in next version
