### ISSUE TITLE
Does not go into the purse.

### ISSUE THREAD

**Issue by BoLODbKA** [semuxproject/semux#291]
Does not go into the semux
I already wrote this problem, but for some reason they did not answer me and deleted the post. The problem still remains. Does not open the wallet. I try already with 4 laptops.
I think that this is a big problem.
To come it was possible once through a command line Tsmd. No more coming.
Please understand what the error is, I can access the teamviewer
https://discordapp.com/    BoLODbkA

**Comment by BoLODbKA** [comment]
Windows 10 и windows8/    64"

**Comment by BoLODbKA** [comment]
I'm Russian-speaking

**Comment by BoLODbKA** [comment]
After entering the password, the window disappears and does not appear

**Comment by cryptokat** [comment]
Hi @BoLODbKA 
Could you please install the 64bit version of Java and try again?
https://www.java.com/en/download/manual.jsp

**Comment by semuxproject** [comment]
Hi @bolodbka, we are unable to reproduce this problem based on your description. Please PM me on discord. I'm more than happy to help you out.
