### ISSUE TITLE
Stuck after network disconnect

### ISSUE THREAD

**Issue by crimealone** [semuxproject/semux#302]
My windows wallet stops sync if network is disconnected. Have to restart the wallet even if network gets connected.

**Comment by semuxproject** [comment]
The client should be able re-sync after 2 minutes. It will try to get peers information from the seed node every two minutes.

**Comment by obro4469** [comment]
Hi, same problem here. Every time I restart my wireless router, the wallet stucks. I think it's due to dynamic IP. My IP changes everytime the router reconnects to the Internet.

**Comment by obro4469** [comment]
BTW running on WIN7.

**Comment by semuxproject** [comment]
I think you're right. The wallet currently doesn't refresh your IP and thus may cause problems

**Comment by obro4469** [comment]
Thanks for confirmation.

**Comment by semuxproject** [comment]
Addressed in d1c10406f29b1afa5876d31d2072276747b0fe7d

**Comment by semuxproject** [comment]
Fixed
