### ISSUE TITLE
Store raw public key instead of X.509 in signature

### ISSUE THREAD

**Issue by semuxproject** [semuxproject/semux#303]
This will save 12 bytes for every signature

**Comment by cryptokat** [comment]
Is this going to require a backward-incompatible protocol upgrade?

**Comment by semuxproject** [comment]
Yeah, it requires backward-incompatible protocol upgrade, or we only enable this feature when mainnet launches.

**Comment by phash** [comment]
untested to the mainnet? Is it bad to restart RC network?

**Comment by semuxproject** [comment]
Implemented, to be included
