### ISSUE TITLE
wallet-address is not encoded in the TCP traffic

### ISSUE THREAD

**Issue by wg135** [semuxproject/semux#308]
Hi there,

not sure if this is an issue. But the address information is disclosed in the network traffic.

#### System information

Semux version: Semux/v1.0.0-rc.3

OS & Version:  Ubuntu 16.04

#### Expected behaviour
I start to check the Semux and just monitor the network traffic. I think the wallet address should not be disclose in the traffic. 

Description

#### Actual behaviour
Actually my wallet address is showed in the network traffic. Should it be encoded or encrypted before sending?

Description, screenshot allowed
![capture](https://user-images.githubusercontent.com/1268624/33784556-f6507606-dc26-11e7-98d4-96a4df50979b.PNG)

#### Steps to reproduce the behaviour

1. Step one
start wireshark to monitor the traffic, run command : ./unix/semux-cli.sh
2. Step two
follow the TCP traffic and will see the address information 

#### Backtrace

````
[backtrace]
````

**Comment by wg135** [comment]
Don't know if this is okay for the wallet.

**Comment by phash** [comment]
it is the public key, I suppose?

**Comment by semuxproject** [comment]
It's the peer id, hash of the public key.

**Comment by wg135** [comment]
right. it is. I guess it doens't matter
