### ISSUE TITLE
semux.info block explorer bug, doesn't show existing TX 

### ISSUE THREAD

**Issue by Cloudpostru** [semuxproject/semux#319]
semux.info block explorer doesn't show the transaction I got from other member. 
TX shows in his wallet (delegate trgnn 0x0d3a69aca0fff5f434d9a86be09541bf65dd2818) and in my wallet as inbound TX (delegate cloudpost 0x35dd2aab216c8370ee1ac456e1896e1f864b9e5f).

Block height is the same for semux.info and my wallet.
TX hash: 0x50552c5472febf37a426df1381f4e559429e745895dccede92aabbda302db3f4

TX screenshot:
https://gyazo.com/435d604915d6423a51f3913bc2afea4e

Latest stats for explorer for my account:
https://semux.info/explorer/account/0x35dd2aab216c8370ee1ac456e1896e1f864b9e5f

**Comment by semuxproject** [comment]
Should have been fixed
