### ISSUE TITLE
Pending improvements for next upgrade

### ISSUE THREAD

**Issue by semuxproject** [semuxproject/semux#322]
The following improvements will break the consensus, and thus can only be deployed at next upgrade:

* Signature format optimization
* Transaction result
* Change max block size to 1 MB
* Delay the mandatory upgrade
* Increase number of validators to 100
* Increase block reward to 3 SEM
* Change frame header and add data compression 
* Replace sychronizedMap with ConcurrentHashMap
* Replace LRUMap with caffeine cache
* Fix merkle tree issue
* Add replay protection (encode net id in tx)
* Decrease min transaction fee
* Integration test for all transaction types
* BFT integration test: 3 validator + 1 normal
* Enhance reason code
* Enhance closing connection
* Add password confirmation to wallet createion
* TO BE ADDED

**Comment by cryptokat** [comment]
Are we going to have an independent branch for these changes?

**Comment by semuxproject** [comment]
Yes, please PR to the `redstone` branch.

**Comment by semuxproject** [comment]
All changes should be directed to the `develop` branch now.
