### ISSUE TITLE
Wallet exiting due to too small heapsize (Windows x64 RC4 client) 

### ISSUE THREAD

**Issue by GMule2k** [semuxproject/semux#328]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the Discord channel here: https://discord.gg/qQVckKZ

#### System information

Semux version: `e.g., v1.0.0-rc.4`

OS & Version: `Windows 10 x64, 4 core, 8GB Ram`

Wallet exits with error in debug log regarding "Upgrading computer" (seems to be running 3552MB)

#### Steps to reproduce the behaviour

1. Start wallet (enter password)
2. Exits at block dated around 8pm GMT 14 dec 2017

I added the following to the semux.l4j.ini to override and working now
-Xms4096m -Xmx4096m

2017-12-14 22:21:41 [cons] INFO  SemuxBFT - Entered new_height: height = 53164, # validators = 64
2017-12-14 22:21:41 [cons] INFO  SystemUtil - Max allowed JVM heap memory size = 3102 MB
2017-12-14 22:21:41 [cons] ERROR SemuxBFT - You need to upgrade your computer to join the BFT consensus!

EDIT (as can't comment at this time):
Confirmed I was / still am using the 64 bit Java (I don't believe the 32 bit version would have let me set the size so big in any event)

**Comment by cryptokat** [comment]
Hi, Please make sure that you are using 64-bit version of Java.
https://java.com/en/download/manual.jsp

**Comment by semuxproject** [comment]
The benchmark will log if on 32-bit jvm.

It's probably you don't have enough free memory
