### ISSUE TITLE
Support Network Data Compression

### ISSUE THREAD

**Issue by cryptokat** [semuxproject/semux#347]
Network data compression can significantly reduce the network bandwidth consumption of synchronization process. Etheruem saved 60% of network bandwidth by enabling [Snappy](https://github.com/google/snappy) compression on devp2p protocol.

#### References
- https://github.com/ethereum/go-ethereum/pull/15106
- https://github.com/ethereum/ethereumj/pull/947

**Comment by semuxproject** [comment]
This is a good idea. If you can compress the data at message level or frame level, it would be awesome.

**Comment by semuxproject** [comment]
- [ ] Benchmark bandwidth save on transferring the 80K blocks of testnet
- [ ] If positive, add a `SnappyHandler` between `MessageHandler` and `FrameHandler`

**Comment by orogvany** [comment]
This is interesting, so I took a stab at it.
Benchmarking the current net (112,703 blocks) I see

in bytes
current: 741,846,929
snappy: 677,983,912
savings 8.6%

This will probably improve greatly as # of transactions per block goes up, but for now, not impressive gains.

**Comment by semuxproject** [comment]
Also benchmarked the RC net by counting the total size of `BlockMessage`
```
# of blocks      : 119948
Raw size         : 794909102 bytes
Compressed size  : 722519875 bytes
Ratio            : 90.89339563254869 %
Total time used  : 2426320314 ns
Average time used: 20228 ns
```

**Comment by cryptokat** [comment]
Ethereum downloads blocks in batch to lower the number of network round trips which also affects the compression ratio because there are more duplicated data. I implemented a benchmark based on `BlocksMessage` which holds 64 blocks in a single message that improves the compression ratio to 56% https://github.com/cryptokat/semux/commit/d8ae9716e36ca4a382f4610ece515a20bce90d9c:

```
======================================
ALL_BLOCKS
======================================
# of blocks      : 64
# of transactions: 2
Raw size         : 39758 bytes
Compressed size  : 22340 bytes
Ratio            : 56.18994919261532 %
Total time used  : 7229506 ns
Average time used: 112961 ns
```

**Comment by semuxproject** [comment]
Good point. We need to think about syncing in batch.

**Comment by semuxproject** [comment]
Implemented
