### ISSUE TITLE
High memory usage - observed up to 2+Gb

### ISSUE THREAD

**Issue by ocvaad** [semuxproject/semux#35]
Wallet opened 24/7 since update to 1.0.11 Alpha. 
Observed memory usage 2+Gb. 
Expected memory usage is up to 1Gb under normal load. 

Attached screenshot - Windows10X64
![image](https://user-images.githubusercontent.com/32023262/30825859-38bb954e-a23d-11e7-819a-ff10f53f5b1c.png)

**Comment by semuxproject** [comment]
Due to network buffer, which has been fixed by 20d488b423349312b2aa10406c5c980bf5399526
