### ISSUE TITLE
Wallet start is blocked by wallet password dialog - sync/wallet start delayed until correct password input

### ISSUE THREAD

**Issue by ocvaad** [semuxproject/semux#376]
#### System information

Semux version: v1.0.0-rc.5

OS & Version: Windows 2016 X64

#### Expected behavior

Wallet starts/starts syncing immediately after client launch.  
Wallet might be started in already 'Locked' mode - thus will start the wallet sync process immediately. 

#### Actual behavior

Wallet start is blocked by wallet password dialog.

**Comment by semuxproject** [comment]
See #382. Re-download and it should be fixed
