### ISSUE TITLE
Remove select wallet on startup

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux#385]
#### Expected behaviour

There appears to be no reason for the selecting a coinbase wallet on startup.  All activities in the app can be performed on any address you have.  Balance also takes all addresses into consideration.

#### Actual behaviour

You are required to select an option that does not appear to matter.

#### Steps to reproduce the behaviour

1. Create a wallet
2. add an address
3. Note that you can send, recieve, vote delegates for both wallets
4. close and start back up, note that you see 2 selections for wallet.  Upon choosing either one, you can still send, receive, and vote delegates for either wallet.

Sorry if I'm missing some nuance to which account gets coinbase.  It is confusing to users though.

**Comment by semuxproject** [comment]
The coinbase, selected address, is used for identifying node on the network.

**Comment by orogvany** [comment]
Ok. Why does a user care which identifying node they are?  If they aren't running a delegate, why add an extra step to startup?

**Comment by orogvany** [comment]
This can be closed out.  It looks like change was made so if there was only one address, selection would automatically choose the first one.

Thanks!
