### ISSUE TITLE
Password can be changed without knowing old password

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux#386]
#### System information

Semux version: v1.0.0-rc.5

#### Expected behaviour

Need to enter old password correctly before changing password.

#### Actual behaviour

Type anything in for old password, and you can set new password.

#### Steps to reproduce the behaviour

1. Change password
2. Type garbage into old password
3. Congrats, you just changed the password

bug bounty to 0x5c0c8a67ee6c14fa853c4595cd90e57359efe589

**Comment by semuxproject** [comment]
Fixed, to be included.
