### ISSUE TITLE
GUI - Lock/Unlock button reflect wallet state and not action to perform 

### ISSUE THREAD

**Issue by ocvaad** [semuxproject/semux#388]
#### System information

Semux version: v1.0.0-rc.5

OS & Version: Windows 2016 X64

#### Expected behavior

Lock/Unlock button reflect action that can be performed. 

#### Actual behaviour

Button reflects the state of the wallet. 

#### Steps to reproduce the behaviour

Lock walled and observe button label set to Lock. 
![image](https://user-images.githubusercontent.com/32023262/34467045-36e5aa08-eeef-11e7-804e-197775248104.png)

Unlock wallet and observe that button label set to Unlock. 
![image](https://user-images.githubusercontent.com/32023262/34467049-49a0095e-eeef-11e7-9412-bbaa69ba2f7e.png)

**Comment by semuxproject** [comment]
This has been fixed by https://github.com/semuxproject/semux/commit/5e8f07c0c6c62de69a983dff4c43f382360e3e05

**Comment by semuxproject** [comment]
Fixed, to be included
