### ISSUE TITLE
Did not verify the old password

### ISSUE THREAD

**Issue by jezzmemo** [semuxproject/semux#389]
Hi there,

#### System information

Semux version: `semux-macos-1.0.0-rc.5`

OS & Version: `macOS 10.12.6`

#### Expected behaviour

If you change password,the application must check the old password is correct

#### Actual behaviour

If you change password,input nothing,submit form,will show change password successful,

my password change to empty

#### Steps to reproduce the behaviour

1. Open application,select action menu `change password`
2. input nothing,submit,the password will change to empty

**Comment by semuxproject** [comment]
Thanks. This is the same as #386, and is fixed by PR #387
