### ISSUE TITLE
Locked GUI is still accessible via keyboard

### ISSUE THREAD

**Issue by vaskevich** [semuxproject/semux#392]
There might be other ways of mutating the UI while locked, perhaps via OS-specific accessibility utilities. The best option might be to completely unload the UX or disable all widgets/controls during locked mode rather than just overlaying a click-eating screen.

#### System information

Semux version: `v1.0.0-rc.5`

OS & Version: `macOS 10.13.2`

#### Expected behaviour

UI is completely frozen and inoperable while locked.

#### Actual behaviour

Can still navigate and use UI through keyboard nav, e.g., using tab/shift+tab/space.
![](https://cl.ly/2b3j0o2O1339/Screen%20Recording%202018-01-02%20at%2001.54%20AM.gif)

#### Steps to reproduce the behaviour

1. Lock UI
2. Use keys to navigate the UI

0x6df938292ccff9bee5d92cae7a1ae5c22f6038e7

**Comment by semuxproject** [comment]
Fixed, to be included
