### ISSUE TITLE
Clear does not clear Data

### ISSUE THREAD

**Issue by vaskevich** [semuxproject/semux#393]
Minor usability bug.

#### System information

Semux version: `v1.0.0-rc.5`

OS & Version: `macOS 10.13.2`

#### Expected behaviour

Clear button should clear all fields on the screen, including data.

#### Actual behaviour

Data not reset.
![](https://cl.ly/3e2X412H0t41/Screen%20Recording%202018-01-02%20at%2002.06%20AM.gif)

#### Steps to reproduce the behaviour

1. Type in text within data
2. Hit the "Clear" button

0x6df938292ccff9bee5d92cae7a1ae5c22f6038e7

**Comment by semuxproject** [comment]
Fixed, to be included
