### ISSUE TITLE
Copy/Paste doesn't work

### ISSUE THREAD

**Issue by blazer01** [semuxproject/semux#396]
Minor usability bug.

System information
Semux version: v1.0.0-rc.5
OS & Version: Windows 7 x64

#### Expected behaviour

Copy/Paste using context menu (mouse right click) doesn't work on "Add address" window of "Address book" module. 

#### Actual behaviour

There is no context menu popup with Copy/Paste options after clicking right mouse button on the address field of "Add Address" window of "Address Book" module. Probably, it also makes sence to add context menu to "Name" field.

#### Steps to reproduce the behaviour

0. Copy any address to the context buffer.
1. Push "Send" menu button on the main page.
2. Push "Address book" button.
3. Push "Add" button on the "Address book" window.
4. Click right mouse botton on "Address" field. There is no context menu popup.

My addresss is 0x9f0b3262b87d5350b81da69a8f79fd7893f9eff9.
Thank you.

**Comment by semuxproject** [comment]
Fixed, to be included.
