### ISSUE TITLE
Labels of "Name" and "Address" fields are not localized.

### ISSUE THREAD

**Issue by blazer01** [semuxproject/semux#397]
Minor usability bug.

System information
Semux version: v1.0.0-rc.5
OS & Version: Windows 7 x64 (RUSSIAN localization).

#### Expected behaviour
Labels "Name" and "Address" fields are not localized on "Add address" window of "Address book" module.

#### Actual behaviour
![image](https://user-images.githubusercontent.com/35062991/34517529-6f939146-f08c-11e7-9c28-f44dd9d2bcdc.png)

#### Steps to reproduce the behaviour
1. Push "Send" menu button on the main page.
2. Push "Address book" button.
3. Push "Add" button on the "Address book" window. Labels "Name" and "Address" fields are not localized on "Add address" on Russian language.

My addresss is 0x9f0b3262b87d5350b81da69a8f79fd7893f9eff9.
Thank you.

**Comment by cryptokat** [comment]
Translations are maintained in this Crowdin project: https://crowdin.com/project/semux

**Comment by phash** [comment]
@cryptokat the Fields were not localized. I added a small fix for this..

**Comment by cryptokat** [comment]
@phash :ok_hand:

**Comment by semuxproject** [comment]
Fixed, to be included.
