### ISSUE TITLE
Bottons "Cut" and "Paste" must be disabled in popup menu of "Delegate" read only window

### ISSUE THREAD

**Issue by blazer01** [semuxproject/semux#399]
Minor usability bug.

System information
Semux version: v1.0.0-rc.5
OS & Version: Windows 7 x64 (RUSSIAN localization).

#### Expected behaviour
Bottons "Cut" and "Paste" must be disabled in popup menu of "Delegate" read only window. See the image below:
![image](https://user-images.githubusercontent.com/35062991/34518642-48ebefd4-f091-11e7-9d80-4cf2931575e6.png)

#### Steps to reproduce the behaviour
1. Open "Delegates" tab.
2. Double click any delegate.
3. In "Delegate" read only window open popup menu on delegate's name or address.
4. Popup menu has Cut, Copy and Paste active buttons.

My addresss is 0x9f0b3262b87d5350b81da69a8f79fd7893f9eff9.
Thank you.

**Comment by semuxproject** [comment]
Fixed, to be included in main release
