### ISSUE TITLE
get_account_transactions returns duplicated transactions

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux#403]
#### System information

Semux version: v1.0.0-rc.5

OS & Version: osx

#### Expected behaviour

Transaction hashes should not be duplicated in get_account_transactions calls.  if folks use the API to tally delegate votes, they'll get double values, so this will hurt pool operators.  It might happen for transactions as well, but I just noticed these two (and checked a few other delegates to see same behavior)

#### Actual behaviour

duplicate hashes can be returned.

#### Steps to reproduce the behaviour

1. http://localhost:5171/get_account_transactions?address=0x0000000d007c97af435bc78b3011d2228fc68d6f&from=0&to=10000 (or it seems most delegate registrations are duplicated)
2. note duplicated transactions returned for
0x962eb6137b7e6eaffe3d3afaa8e4419e44f4cd4e3662f6357517569e361ca939 (type=delegate)
0x917e652b5bfdb3271e78716d6e17ddd06d6836cc4acb8608fe095ed3d20b22bf (type=vote)

BB - 0x5c0c8a67ee6c14fa853c4595cd90e57359efe589

**Comment by cryptokat** [comment]
I am not sure if I get you right, but there is only one transaction with the hash `0x962eb6137b7e6eaffe3d3afaa8e4419e44f4cd4e3662f6357517569e361ca939` found in my wallet:

```
➜  ~ curl http://user:pass@localhost:5171/get_account_transactions\?address\=0x0000000d007c97af435bc78b3011d2228fc68d6f\&from\=0\&to\=10000 | jq '.result[] | select(.hash | contains("0x962eb6137b7e6eaffe3d3afaa8e4419e44f4cd4e3662f6357517569e361ca939"))'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  579k  100  579k    0     0  5005k      0 --:--:-- --:--:-- --:--:-- 5041k
{
  "hash": "0x962eb6137b7e6eaffe3d3afaa8e4419e44f4cd4e3662f6357517569e361ca939",
  "type": "DELEGATE",
  "from": "0x0000000d007c97af435bc78b3011d2228fc68d6f",
  "to": "0x0000000d007c97af435bc78b3011d2228fc68d6f",
  "value": 1000000000000,
  "fee": 50000000,
  "nonce": 0,
  "timestamp": 1511447731172,
  "date": "2017-11-23 14:35:31",
  "data": "0x726f7879"
}
```

**Comment by orogvany** [comment]
<img width="798" alt="screen shot 2018-01-03 at 7 07 11 am" src="https://user-images.githubusercontent.com/24282143/34525715-c2f5e77c-f054-11e7-87ea-0d468b550987.png">

Hm, shows up 2 for me

**Comment by semuxproject** [comment]
Fixed, to be included
