### ISSUE TITLE
Balance of removed account is still available on the "Main" tab.

### ISSUE THREAD

**Issue by blazer01** [semuxproject/semux#405]
System information
Semux version: v1.0.0-rc.5
OS & Version: Windows 7 x64 (RUSSIAN localization).

#### Expected behaviour
Information (balance) of removed account must be removed everywhere.

#### Actual behaviour
Balance of removed account is still available on the main page.

#### Steps to reproduce the behaviour
1. Login to wallet with 2+ accounts (Account #0, Account #1). During login choose account #0 (first account).
2. Remove Account #0 (first account) on "Receive" tab .
3. The coinbase "Account #0" is still available on the "Main" tab. I think you should set "Not Available" instead of "Account #0" in Coinbase field.

My address is 0x9f0b3262b87d5350b81da69a8f79fd7893f9eff9.
Thank you.

**Comment by semuxproject** [comment]
Same as #406
