### ISSUE TITLE
Accounts with the same number don't match on "Main" and "Receive" tabs.

### ISSUE THREAD

**Issue by blazer01** [semuxproject/semux#406]
System information
Semux version: v1.0.0-rc.5
OS & Version: Windows 7 x64 (RUSSIAN localization).

#### Expected behaviour
Accounts with the same number must have the same balance on the "Main" tab and "Receive" tab.

#### Actual behaviour
Under certain circumstances, same accounts on "Main"  tab and "Receive" tab have different balance.

#### Steps to reproduce the behaviour
1. Login to wallet with 2+ accounts (Account #0, Account #1). During login choose account #0 (first account).
2. Remove Account #0 (first account) on "Receive" tab.
3. The balance on "Account #0" on "Main" and "Receive" tabs doesn't match.

My addresss is 0x9f0b3262b87d5350b81da69a8f79fd7893f9eff9.
Thank you.

**Comment by semuxproject** [comment]
TODO: display coinbase as `0x1122...3344`

**Comment by semuxproject** [comment]
Resoved, to be included
