### ISSUE TITLE
Test of ProgressFormatter fails due to localization error

### ISSUE THREAD

**Issue by phash** [semuxproject/semux#407]
`[ERROR] Failures: 
[ERROR] org.semux.gui.panel.HomePanelTest.testProgressFormatter(org.semux.gui.panel.HomePanelTest)
[ERROR]   Run 1: HomePanelTest.testProgressFormatter:66 expected:<12[.]3 %> but was:<12[,]3 %>
[ERROR]   Run 2: HomePanelTest.testProgressFormatter:66 expected:<12[.]3 %> but was:<12[,]3 %>
[ERROR]   Run 3: HomePanelTest.testProgressFormatter:66 expected:<12[.]3 %> but was:<12[,]3 %>`

#### Actual behaviour

Test fails due to localization / format mismatch

#### Steps to reproduce the behaviour

1. Step set locale to GERMAN
2. Step run tests

**Comment by semuxproject** [comment]
Fixed, to be included.
