### ISSUE TITLE
QR-code of last removed address  is still available

### ISSUE THREAD

**Issue by blazer01** [semuxproject/semux#409]
#### System information
Semux version: v1.0.0-rc.5
OS & Version: Windows 7 x64 (RUSSIAN localization).

#### Expected behaviour
When you remove account on "Receive" tab, the corresponding address must be deleted. 

#### Actual behaviour
When you remove **last** account on "Receive" tab, the corresponding address is still available through QR-code in the top right corner.

#### Steps to reproduce the behaviour
![bug1](https://user-images.githubusercontent.com/35062991/34535455-e4476b7a-f0d2-11e7-9bab-c94e53c97748.gif)

My address is 0x9f0b3262b87d5350b81da69a8f79fd7893f9eff9.
Thank you.

**Comment by semuxproject** [comment]
Fixed, to be included in main release
