### ISSUE TITLE
"Address book" window must be always on top

### ISSUE THREAD

**Issue by blazer01** [semuxproject/semux#414]
#### System information
Semux version: v1.0.0-rc.5
OS & Version: Windows 7 x64 (RUSSIAN localization).

#### Expected behaviour
"Address book" window must be always on top, otherwise it is possible to open multiple "Address book" windows.

#### Steps to reproduce the behaviour
![bug2](https://user-images.githubusercontent.com/35062991/34543027-01d87b9e-f0f0-11e7-8050-4aacc456fafa.gif)

My address is 0x9f0b3262b87d5350b81da69a8f79fd7893f9eff9.
Thank you.

**Comment by semuxproject** [comment]
Thanks. Will be fixed in main release.
