### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Messier81z** [semuxproject/semux#419]
Java process running SemuxGUI consumed 18G of resident memory. 

#### System information

Semux version: Semux/v1.0.0-rc.5/Linux/amd64

OS & Version: Ubuntu 16.04

#### Expected behaviour

Not to grow memory consumption over time.

#### Actual behaviour

Consumed 18G of ram over a space of few days.

#### Backtrace

top

42.084g 0.018t      0 S  21.6 59.8   1036:01 /usr/lib/jvm/java-9-oracle/bin/java -Xmx14154M -cp semux.jar org.semux.gui.SemuxGUI

**Comment by semuxproject** [comment]
If possible, could you please run `jconsole` to analyze how memory are being used, or give us some snapshot? This would help us diagnose the problem.

**Comment by Messier81z** [comment]
top again after running it for 15h - 5G and growing

20   0 26.967g 5.202g  28796 S  42.3 16.6 159:39.90 /usr/lib/jvm/java-9-oracle/bin/java -Xmx15683M -cp semux.jar org.semux.gui.SemuxGUI

**Comment by Messier81z** [comment]
2h later...

20   0 27.670g 5.621g  24120 S  19.2 18.0 193:23.36 /usr/lib/jvm/java-9-oracle/bin/java -Xmx15683M -cp semux.jar org.semux.gui.SemuxGUI

![screenshot_2018-01-05_12-24-45](https://user-images.githubusercontent.com/33009588/34609190-915db670-f213-11e7-81f5-2ed9e7b0d900.png)

**Comment by orogvany** [comment]
If you go to MBeans, com.sun.management, HotSpotDiagnosis, Operations, dumpHeap and give it a filename you can take a heap dump that can be analyzed.

However, your priv keys will be in this heapdump, so doing it with a fresh/empty wallet would be ideal.
On the Overview tab you can see # Threads.  What's it at?

On mine, after running for 10 minutes or so, its at 110, which feels high, as there's only 30 peers.

I checked an instance that had been running for days, and it had crashed :/

**Comment by orogvany** [comment]
Yea, looks like a thread leak.
I think this may be in 
SystemUtil.getIp doesnt close the NioEventLoopGroup that it creates

but more verification is needed on my side

**Comment by Messier81z** [comment]
Cool, does this mean you can reproduce it?

**Comment by orogvany** [comment]
I see threads continue to grow past 200, memory grows along with, so its a likely cause.  Ill have to let it run awhile with/without proposed fix and see if memory stays flat.  Could be a different issue but this seems worth trying.

**Comment by semuxproject** [comment]
Thanks. The NioEventLoopGroup threads are indeed not shut down properly.

**Comment by orogvany** [comment]
Np.  Glad that was it.

0x5c0c8a67ee6c14fa853c4595cd90e57359efe589
