### ISSUE TITLE
Testnet Faucet

### ISSUE THREAD

**Issue by cryptokat** [semuxproject/semux#427]
As we are running a real testnet based on version 1.0 of Semux wallet, a testnet faucet is needed to automate the distribution of testing tokens for developers.

#### References

- https://testnet.manu.backend.hamburg/faucet
- https://faucet.rinkeby.io

**Comment by semuxproject** [comment]
Will set up a testnet faucet after the main net is launched.

For now, please post Semux address here and I will manually sent testnet coins.

**Comment by cryptokat** [comment]
@semuxproject 
My testnet address: `0xce52d798aedb4e39327b0fef01cf18c0aaa1a4fc`
Thanks!

**Comment by bjguillot** [comment]
@semuxproject 

Please send testnet coins to my testnet address:
0xba87e51cb95a6cd4cf42d46b64ea94e3dfdd4d51

(Discord user joyteq#3002)

**Comment by cryptokat** [comment]
Thanks to @honeycrypto 
We have an official testnet faucet now:
- https://www.semux.org/testnetfaucet
- https://github.com/honeycrypto/semux.org-backend
