### ISSUE TITLE
Security issue: An unauthorized user can substitute any destination address in the "Address Book"

### ISSUE THREAD

**Issue by blazer01** [semuxproject/semux#428]
#### System information
Semux version: v1.0.0-rc.5
OS & Version: Windows 7 x64 (RUSSIAN localization).

#### Actual behaviour
1) An unauthorized user or malicious software can substitute any destination address in the "Address Book"  using GUI or directly in addressbook.json file. It makes sense to encrypt "name" and "address" using "password" and add these data to "wallet.data" file. Otherwise, a false address can be used to defraud wallet's owner. The user has to check the destination address before each transaction even if he uses inner address book.
2) Only private keys are encrypted in "wallet.data" file. If a false address will be specified in a "wallet.data" by malicious software then a user losts SEM if he decides to redistribute SEM between his accounts. 

My address is 0x9f0b3262b87d5350b81da69a8f79fd7893f9eff9.
Thank you.

**Comment by phash** [comment]
good point

maybe sign the address with users priv key?

**Comment by semuxproject** [comment]
Q1: this requires the computer being hacked/used by unauthorized users. 

Q2: the public key can be calculated from the the private key, and is only used for double checking the private key.

That said, if a hacker/unauthorized user has access to your operating system, he can simply delete the wallet file. Backup is the only solution.

**Comment by semuxproject** [comment]
Address aliases are encrypted since v1.0.0
