### ISSUE TITLE
Any focused item must be highlighted in a drop-down list.

### ISSUE THREAD

**Issue by blazer01** [semuxproject/semux#430]
#### System information
Semux version: v1.0.0-rc.5
OS & Version: Windows 7 x64 (RUSSIAN localization).

#### Expected behaviour
Any focused item must be highlighted in a drop-down list.

#### Actual behaviour
If you put mouse over any item in the drop-down list and wait 2-3 seconds, the highlight jumps to the coinbase acc. It's true for drop-down lists on "Send" and "Delegates" tab.

#### Steps to reproduce
![bug3](https://user-images.githubusercontent.com/35062991/34606431-622c12d6-f220-11e7-9ec6-75d5f93ee254.gif)

My address is 0x9f0b3262b87d5350b81da69a8f79fd7893f9eff9.
Thank you.

**Comment by semuxproject** [comment]
Resolved
