### ISSUE TITLE
Locking and Unlocking

### ISSUE THREAD

**Issue by RevenantLuke** [semuxproject/semux#431]
![unbenannt1](https://user-images.githubusercontent.com/35142824/34615653-ec4c7c7a-f235-11e7-8435-490da29c59ac.PNG)
![unbenannt](https://user-images.githubusercontent.com/35142824/34615655-ed80d8b6-f235-11e7-8bec-0a1327f0c0b1.PNG)

Hi there,
while testing the Wallet I came across the lock and unlock functions. I am not sure if there is a german version or not but when the wallet is unlockend and I can work in it, in the top right corner it says Unlock. When clicking it it locks the wallet and says Sperren. I would switch those up so when clicking lock it locks the wallet and whne clicking unlock it unlocks it. If it is ment so that the wallet is currently unlocked then I would make the text say unlocked and lockend. Currently Mine says Unlock in english but Sperren in German. While this is a german version of the Wallet it should be kept in all german :)

**Comment by orogvany** [comment]
It looks like this was added in the develop branch
Lock=Sperren
Unlock=Entsperren

But does not exist in the last RC branch.  They're still working on the localization. So this will be fixed next update :D

**Comment by semuxproject** [comment]
This has been addressed in develop branch and will be included in the next release
