### ISSUE TITLE
Docs: get_validators return type does not match in wiki

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux#438]
#### Expected behaviour

get_validators returns a list of validator addresses
Documentation should show it as such

#### Actual behaviour

get_validators

Returns a list of validators
Parameters

None
Returns

    result - array of delegate

**Comment by orogvany** [comment]
Also return  type of get_account does not match

**Actual**
    result - number

**Expected**
"result": {
    "address": "0x837c1e6ceca4ccad20e59849cb7a9678394f7313",
    "available": 6652028306462,
    "locked": 100000000000,
    "nonce": 761
  }

**Comment by semuxproject** [comment]
Resolved
