### ISSUE TITLE
Semux v1.0.0-beta

### ISSUE THREAD

**Issue by ashipka11** [semuxproject/semux#44]
block 13836
![image](https://user-images.githubusercontent.com/21366809/31250862-cb1c2f4a-aa24-11e7-8127-e35f6de38f19.png)
![image](https://user-images.githubusercontent.com/21366809/31250880-d56bb16e-aa24-11e7-833b-8d9a8a1db044.png)

**Comment by semuxproject** [comment]
This is the same issue as in #43
