### ISSUE TITLE
Data field data encoding is confusing/inconsistent

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux#440]
#### System information

Semux version: v1.0.0

#### Expected behaviour

On the send dialog, there is a field for data.
If i enter 0x(hex data)
this gets encoded again, so it can't really be used for raw hex from client.

If we expect this to be something human legible for a note for payment
If I go to transactions and view it, I should get both the hex and the unencoded version
So the receiving side can actually view it.

I would expect either a hex decoded version to also be shown on transaction history
or some way for it to be able to enter hex values on sending panel.  

Right now, there's no useful way for the user to interact with this from both sending and receiving side.  From API side it makes sense, but from GUI, it's confusing how it should be used.

#### Actual behaviour

sent values are sent hex encoded, but there's no way for user to view the data
without decoding it in separate application

**Comment by semuxproject** [comment]
Resolved
