### ISSUE TITLE
Overview status should show status=Delegate vs Validator

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux#441]
#### System information

Semux version: 1.0.0RC5

#### Expected behaviour

Currently it shows if you are running as a delegate, but does not indicate if you qualify as a validator.  Should be easy to denote Normal and Validator vs Delegate

Additionally, if Validator, it would be nice to see forged, hit,miss stats here.  currently these are unavailable in GUI, and only available via REST API.

Most users will never be a delegate or validator, so seeing Status: Normal could be construed as the connection working, at a normal status.  Renaming this to "Wallet" or "User" would be beneficial as well

#### Actual behaviour

Shows delegate even if validator

**Comment by semuxproject** [comment]
I'm working on this
