### ISSUE TITLE
Might a bug on Changing password in Wallet

### ISSUE THREAD

**Issue by wzcbjfu** [semuxproject/semux#442]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the Discord channel here: https://discord.gg/qQVckKZ

#### System information

Semux version: `e.g., v1.0.0-rc.5`

OS & Version: `e.g., Windows 10 64bit Chinese

Commit hash : `git rev-parse HEAD` (optional)

#### Expected behaviour

I use the wallet with Chinese UI. When I try to change my password. it require 3 lines to fill.
1.current password
2.new
3.new again

#### Actual behaviour

I found that I could fill anything in line 1 even with blank. I did had my new password changed.

#### Steps to reproduce the behaviour

see up

#### Backtrace

````
[backtrace]
````
0x27056dc1fa1b35f84e556c1c65941cc8e6b1bfac
thank you, if I helped

**Comment by semuxproject** [comment]
Same issue as #389
