### ISSUE TITLE
Password lost when update new version wallet

### ISSUE THREAD

**Issue by gwzz** [semuxproject/semux#447]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the Discord channel here: https://discord.gg/qQVckKZ

#### System information

Semux version: ` v1.0.0-rc.4, v1.0.0-rc.5`

OS & Version: ` macOS 10.12.6`

Commit hash : `git rev-parse HEAD` (optional)

#### Expected behaviour

I updated semux from rc.4 to rc.5 and imported old wallet file. I expect to use the old password, but it disappeared. No password needed to enter the wallet.

#### Actual behaviour

Import wallet to the new version, and lost old password. Just no password.
I think it is a security problem. If anyone gets a wallet file, then he can get the money. 
Can you add a feature like when you backup wallet, also need the old password or some similar validation method?

#### Steps to reproduce the behaviour

1. download rc.5.
2. backup wallet from rc.4
3. open rc5 and import backup wallet
4. sync and close rc5, delete rc4
5. reopen rc5

#### Backtrace

````
[backtrace]
````

Wallet: 0x10e2e7b532d89a366cce7203050a81acad9c66f2

**Comment by semuxproject** [comment]
Confirmed. When recovering the accounts at welcome window, the old password is not kept after recovering.
