### ISSUE TITLE
add_to_blacklist doesn't appear to work

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux#450]
#### System information

Semux version: 1.0.0 (develop)

#### Expected behaviour

if I call getPeers, see a peer with a given address, then call add_to_blacklist
I expect that the connection with them will drop.

However, the number of peers does not change, and they still show up in getPeers.
On restart, nothing changes either.

I note that ipfilters.json is not updated.

#### Actual behaviour

peers seem unaffected by blacklisting

#### Steps to reproduce the behaviour

1. on testnet, getPeers
2. find one, blacklist it, call getPeers again

0x5c0c8a67ee6c14fa853c4595cd90e57359efe589

**Comment by cryptokat** [comment]
TODOs:
- [ ] enable persistency of SemuxIpFilter
- [ ] drop existing peers matching the filter added from `/add_to_blacklist`
