### ISSUE TITLE
error button "голосовать"

### ISSUE THREAD

**Issue by SHAADA** [semuxproject/semux#452]
при нажатии кнопки "голосовать"
появляется окно с надписью 
"У Вас недостаточно средств для снятия голоса, продолжить?"
а
при нажатии на кнопку "отозвать голос"
"Транзакция отправлена, Требуется не менее 30 секунд для обработки!"

то есть кнопки поменяны местами.

**Comment by SHAADA** [comment]
0xb016bc27a0d8396ba947fd85e7d51867020b9e69

**Comment by SHAADA** [comment]
0xb016bc27a0d8396ba947fd85e7d51867020b9e69

**Comment by testzcrypto** [comment]
Messages translated correctly, @SHAADA report that it's shown wrong messages, when user click on **Vote** button it's shows "You will not have enough balance to **unvote**, continue?" when user click on Unvote - "Transaction sent. It takes at least {0}s to get processed!"

Requared additional check.

**Comment by SHAADA** [comment]
version wallet semux-windows-1.0.0-rc.5
