### ISSUE TITLE
"Trunsaction" window displays "Data" field as a byte code

### ISSUE THREAD

**Issue by blazer01** [semuxproject/semux#455]
####System information
Semux version: v1.0.0-rc.5
OS & Version: Windows 7 x64 (RUSSIAN localization).

####Actual behaviour
"Trunsaction" read only window on "Trunsaction" tab displays "Data" field as a byte code. "Data" value must be decoded.

####Steps to reproduce
![image](https://user-images.githubusercontent.com/35062991/34670758-c17a77ae-f488-11e7-9104-e8ddd8d83337.png)

My address is 0x9f0b3262b87d5350b81da69a8f79fd7893f9eff9.
Thank you.

**Comment by orogvany** [comment]
same as #440

**Comment by semuxproject** [comment]
Resolved
