### ISSUE TITLE
Transaction with less than 0.01 SEM is allowed but transaction value less than 0.01 is not displayed anywhere.

### ISSUE THREAD

**Issue by blazer01** [semuxproject/semux#456]
####System information
Semux version: v1.0.0-rc.5
OS & Version: Windows 7 x64 (RUSSIAN localization).

####Actual behaviour
Transaction with less than 0.01 SEM is allowed but transaction value less than 0.01 is not displayed anywhere.

####Steps to reproduce
![image](https://user-images.githubusercontent.com/35062991/34671608-503b02bc-f48c-11e7-89c6-1172c782fba7.png)
![image](https://user-images.githubusercontent.com/35062991/34671614-5637e20c-f48c-11e7-9805-934a1ce8160e.png)
![image](https://user-images.githubusercontent.com/35062991/34671619-5be89976-f48c-11e7-9e1d-f2232b3f2c2e.png)
![image](https://user-images.githubusercontent.com/35062991/34671652-713acfa6-f48c-11e7-9c56-bd46ae922058.png)

My address is 0x9f0b3262b87d5350b81da69a8f79fd7893f9eff9.
Thank you

**Comment by orogvany** [comment]
This is resolved in the 1.0.0 release.  Thanks!
