### ISSUE TITLE
Integration Test failure: org.semux.windows.Launch4jWrapperIT

### ISSUE THREAD

**Issue by mangalpur** [semuxproject/semux#465]
Hi Guys,

#### System information

Semux version: 1.0.0-rc.5

OS & Version: Windows 8

Commit hash : 22c5b06609782fb3da0149e0669ed4797697d2a3

#### Expected behaviour
 1) Launch4jWrapperIT.testLaunch4jWrapper should pass

#### Actual behaviour
Integration test(Launch4jWrapperIT.testLaunch4jWrapper) does not pass .

Please see the screenshot of the integration test
![image](https://user-images.githubusercontent.com/30091639/34801082-92c778f8-f65e-11e7-9f23-6b5ba9e11b39.png)

#### Steps to reproduce the behaviour

I. Follow the instructions specified in https://github.com/semuxproject/semux - See Build from source section
```
- git clone https://github.com/semuxproject/semux
- cd semux
- mvn install
```
or

Just run the Integration test Launch4jWrapperIT.testLaunch4jWrapper.

#### Backtrace
The below code seems to be the problem, which I picked up from Launch4jWrapperIT.java
````
Path prefix = Paths.get(System.getProperty("user.dir"), "dist", "windows");
Path semuxExePath = Paths.get(prefix.toString(), "semux.exe");
````
It is expecting the folders dist and windows, under which semux.exe is expected, But I cant find dist folder under semux(this is where we issue mvn install command).

See screenshot of folder structure
![image](https://user-images.githubusercontent.com/30091639/34801472-e23d2412-f660-11e7-8f28-8e1e1b87127b.png)

**Note:**
I can see semux.exe under target folder

See screenshot below
![image](https://user-images.githubusercontent.com/30091639/34801634-a5baec94-f661-11e7-8ae7-53377ba4dc73.png)

**Comment by cryptokat** [comment]
Hi, Thanks for reporting this.
In CI the testing script executes the following commands to avoid the error you had:
1. `mvn install -DskipTests=true`: this creates the semux.exe in dist folder
2. `mvn test`

**Comment by mangalpur** [comment]
Thanks for the info. I am able to run the integration tests after changing the value as specified in the fix 

`  Path prefix = Paths.get(System.getProperty("user.dir"), "target");`
