### ISSUE TITLE
Validator can diverge from network and not recover (logs attached)

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux#477]
#### System information

Semux version: 1.0.0-RC5

OS & Version: OSX

#### Expected behaviour

Validator should accept voted block, and not diverge from network.  Unsure if current validator is the one voting NO for a block, but once it diverges, it does not recover.  Unsure how to to recover validator at this point.

It's interesting that the validator enters 'syncing' at that point.

#### Actual behaviour

[badValidator.txt](https://github.com/semuxproject/semux/files/1627995/badValidator.txt)

bad stuff happens, no logging occurs, and validator is detached from state and does not recover.
logs continue like that forever.

Let me know how I can help. I have the errant database and rest of logs saved off.

#### Steps to reproduce the behaviour

1. unknown

**Comment by semuxproject** [comment]
Turn on DEBUG logs and figure out why the synced block is not imported (there are many reason for invalid block).

Investigate the last block 130127 if possible.

**Comment by orogvany** [comment]
Ok, will turn on debug and check logs for that block.

**Comment by orogvany** [comment]
Unfortunately, while I do have the database, I cannot reproduce this locally.
When trying to start the validator locally, it'll just spew
Received DISCONNECT msg, reason = DUPLICATE_PEER_ID

Even after stopping the validator on the server.

However, I would argue that logging the reason why a delegate will be dropped from being able to perform concensus again (denying a block on sync), this should be logged at ERROR level.

I guess, even for normal validator voting NO to a block, that logging at WARN/ERROR the very specific reason for the vote is important.

**Comment by semuxproject** [comment]
Most likely, your database is corrupted
