### ISSUE TITLE
Add an address book for recepeints accounts

### ISSUE THREAD

**Issue by aocolitii** [semuxproject/semux#478]
#### System information

Semux version: v1.0.0-rc.5

OS & Version: Windows 10 64 bit

#### Expected behaviour

I want to manage my recepeints accounts in one place.
For example: exchange1, exchange2, Bob's Account etc.

#### Actual behaviour

No such functionality

#### Steps to reproduce the behaviour

It is an input field on Send page instead of a separate page

**Comment by semuxproject** [comment]
Address book is already implemented.
