### ISSUE TITLE
PC crashed with driver related error - \P2P\peers.data file values set to NULL

### ISSUE THREAD

**Issue by ocvaad** [semuxproject/semux#48]
After PC crashed with driver related error, client was unable to connect to testnet. 
Following suggestion by mdodong, checked peers.data file - peers.data file values set to NULL. 
File replaced by peers.data from previous version and client synced. 

This is peers.data after pc crash:
![image](https://user-images.githubusercontent.com/32023262/31321990-212c2a2e-ac97-11e7-8d12-393334197eae.png)

**Comment by semuxproject** [comment]
Peers are not persisted any more.
