### ISSUE TITLE
Allow to assign nicknames to my account on Receive page

### ISSUE THREAD

**Issue by aocolitii** [semuxproject/semux#483]
#### System information

Semux version: v1.0.0-rc.5

OS & Version: Windows 10 64 bit

#### Expected behaviour

User should be able to associate accounts with nicknames

#### Actual behaviour

I have remember the purpose of each account

#### Steps to reproduce the behaviour

1. Click on New Account
2. There is no way to provide a nickname

**Comment by orogvany** [comment]
duplicates #375
