### ISSUE TITLE
Not clear what Status V or Status S means on Delegates page

### ISSUE THREAD

**Issue by aocolitii** [semuxproject/semux#484]
#### System information

Semux version: v1.0.0-rc.5

OS & Version: Windows 10 64 bit

#### Expected behaviour

Metadata in Delegates page should be clear for new users

#### Actual behaviour

V and S are hard to undertand

#### Steps to reproduce the behaviour

1. Click on Delegates page
2. Try to understand what V and S means

**Comment by semuxproject** [comment]
Same as #441
