### ISSUE TITLE
There is no way to export information from Delegates page

### ISSUE THREAD

**Issue by aocolitii** [semuxproject/semux#485]
#### System information

Semux version: v1.0.0-rc.5

OS & Version: Windows 10 64 bit

#### Expected behaviour

User should be able to export to excel information about all Delegates for future planning

#### Actual behaviour

I have to select all, copy & paste to excel and apply additional formatting.

#### Steps to reproduce the behaviour
1. Open Delegates page
2. There is no Export to Excel button

**Comment by phash** [comment]
this can be done by Rest-API Call - earlier requests where pointed there, too

**Comment by orogvany** [comment]
in the new version, the console can also be used
getDelegates

<img width="574" alt="screen shot 2018-03-05 at 6 32 29 pm" src="https://user-images.githubusercontent.com/24282143/37011147-a4ed88b4-20a3-11e8-911a-0a4f959c602f.png">

**Comment by orogvany** [comment]
I think this can be closed.

**Comment by cryptokat** [comment]
resolved by #472
