### ISSUE TITLE
Lock and Unlock issue

### ISSUE THREAD

**Issue by aocolitii** [semuxproject/semux#486]
#### System information

Semux version: v1.0.0-rc.5

OS & Version: Windows 10 64 bit

#### Expected behaviour

Lock and Unlock should behave like toggle

#### Actual behaviour

Lock is switched to Unlock after click, but is not switched back to Lock after entering a password

#### Steps to reproduce the behaviour
1. Click on Lock
2. Enter password
2. See that status is still Unlock

**Comment by ocvaad** [comment]
Related to fixed issue:
https://github.com/semuxproject/semux/issues/388
