### ISSUE TITLE
Put approximate time to finish for first time synching

### ISSUE THREAD

**Issue by aocolitii** [semuxproject/semux#488]
#### System information

Semux version: v1.0.0-rc.5

OS & Version: Windows 10 64 bit

#### Expected behaviour

User needs to understand how long first time syncing will take

#### Actual behaviour

I can see only Peers and percentage.

#### Steps to reproduce the behaviour
1. Open Semux Wallet
2. Try to calculate avg speed of syncing (how many blocks in what timespan)

**Comment by orogvany** [comment]
This is tricky, as block sizes change over time.  For example, syncing bitcoin's block chain from 0-200,000 takes only an hour, but going from 400,000 to 401,000 can take that same amount.

**Comment by cryptokat** [comment]
Bitcoin's implementation for reference:
![selection_148](https://user-images.githubusercontent.com/32390172/35346650-ca595ba0-016d-11e8-9440-ae6c1cabb8bc.png)
