### ISSUE TITLE
Menu is not reacting on Alt + 

### ISSUE THREAD

**Issue by aocolitii** [semuxproject/semux#489]
#### System information

Semux version: v1.0.0-rc.5

OS & Version: Windows 10 64 bit

#### Expected behaviour

User should be able to rely on Alt + for menu navigation

#### Actual behaviour

Nothing is happening if I click on Alt + W for example

#### Steps to reproduce the behaviour
1. Hold Alt + W in order to open Wallet menu

**Comment by phash** [comment]
I could implement mnemonic keys if needed

**Comment by cryptokat** [comment]
resolved by #589
