### ISSUE TITLE
Validators should be removed after x time of inactivity

### ISSUE THREAD

**Issue by MorgUK** [semuxproject/semux#49]
It makes sense to remove inactive validators and replace with active and ready to go delegates. It not only provides a fairer system to all delegates but also will increase chain resiliency and reduce latency.

**Comment by MorgUK** [comment]
Currently only 16 of 40 validators are online.

**Comment by semuxproject** [comment]
This topic needs more R&D.

1. The ``connected`` is obviously making confusion; consider removing the column and provide official stats about validators; 
2. Slash byzantine delegates (not participating in the validation process; proposing false blocks; not voting responsibly).

**Comment by semuxproject** [comment]
The connected column has been removed and validator stats were added.
