### ISSUE TITLE
Blockchian availablilty status on all pages

### ISSUE THREAD

**Issue by aocolitii** [semuxproject/semux#492]
#### System information

Semux version: v1.0.0-rc.5

OS & Version: Windows 10 64 bit

#### Expected behaviour

Sometimes my internet is pretty bad or maybe peers were lost. I want to see that I am still connected to blockchain while sending money or looking at delegates. Peers, Syncing etc. can be moved to right bottom corner and can be available on all pages.

#### Actual behaviour

I have to click to Home every time in order to check the status of network and blockchain.

#### Steps to reproduce the behaviour
1. Keep clicking on Home button in order to be sure that you are connected

**Comment by cryptokat** [comment]
resolved by #717
