### ISSUE TITLE
R-click menu doesn't make any sense in transaction popup on Transactions page

### ISSUE THREAD

**Issue by aocolitii** [semuxproject/semux#494]
#### System information

Semux version: v1.0.0-rc.5

OS & Version: Windows 10 64 bit

#### Expected behaviour

R-click and only Copy as an option

#### Actual behaviour

R-click and you have 3 options: Cut, Copy and Paste. This is readonly popup.

#### Steps to reproduce the behaviour
1. Open Transactions page
2. Double click on transaction
3. R-click on form
4. You see Cut Copy Paste

**Comment by orogvany** [comment]
This is fixed in mainnet release.  Only copy will show up.

Thanks!
