### ISSUE TITLE
There is no status Pending for transaction that user just sent

### ISSUE THREAD

**Issue by aocolitii** [semuxproject/semux#495]
#### System information

Semux version: v1.0.0-rc.5

OS & Version: Windows 10 64 bit

#### Expected behaviour

I sent a transaction and there is no visual status. It's like gone or something just disappeared. I want to see the fact that transaction is preparing for the next block or just like Pending status is fine. Cause the delay is about 30 sec and user will send another another another transaction. 

#### Actual behaviour

No visual sign that transaction was sent in first 30 seconds

#### Steps to reproduce the behaviour
1. Open Send page
2. Prepare and send a transaction
3. Click Home or Transactions page
4. It's empty for 30 seconds (it creates wrong impression)

**Comment by orogvany** [comment]
This is fixed in develop branch, and will go out with mainnet.

Thanks!
