### ISSUE TITLE
Incoming transaction has Nonce (2302), but outgoing is 0

### ISSUE THREAD

**Issue by aocolitii** [semuxproject/semux#496]
#### System information

Semux version: v1.0.0-rc.5

OS & Version: Windows 10 64 bit

#### Expected behaviour

I assume (based on Ether) that incoming and outgoing transactions should have Nonce.

#### Actual behaviour

Only incoming transaction has a Nonce

#### Steps to reproduce the behaviour
1. Send a transaction
2. Check transaction details
3. Nonce is 0

**Comment by semuxproject** [comment]
This is fine. Nonce is the Nth transaction of the sender
