### ISSUE TITLE
Display Vote/Unvote transactions on Main Page too

### ISSUE THREAD

**Issue by aocolitii** [semuxproject/semux#498]
#### System information

Semux version: v1.0.0-rc.5

OS & Version: Windows 10 64 bit

#### Expected behaviour

User want's to see all types of transactions on Main page.

#### Actual behaviour

I can see only Transfer transactions on Main page.

#### Steps to reproduce the behaviour
1. Open Delegates page
2. Select a random delegate
3. Vote for this candidate
4. Unvote this candidate
5. Open Transactions page. Check that Transfer, Vote and Unvote transactions are there
6. Open Main page. Only Transfer transactions are there.

**Comment by orogvany** [comment]
This is by design I believe.  Votes/Unvotes do not affect balance, and are just temporary locks.
