### ISSUE TITLE
Program self closes after wallet setup

### ISSUE THREAD

**Issue by webworker01** [semuxproject/semux#511]
After wallet setup, program only asks for password for wallet. After entering password, program closes with no error message.

Win 10 x64 JRE 1.8.0_162 64 bit

**Comment by cryptokat** [comment]
Could you attach your debug.log?

**Comment by webworker01** [comment]
[debug.log](https://github.com/semuxproject/semux/files/1647619/debug.log)

**Comment by cryptokat** [comment]
@webworker01 
Could you perform the following steps:
1. replace all `INFO` with `DEBUG` in `config/logback.xml`
2. start semux.exe
3. attach your `debug.log` here again

**Comment by semuxproject** [comment]
Please re-open this ticket if this also happens to v1.0.0

**Comment by webworker01** [comment]
Still same on v1.0.0 [debug.log](https://github.com/semuxproject/semux/files/1669856/debug.log)

**Comment by cryptokat** [comment]
@webworker01 

According to your debug.log, you are actually using 32bit version of Java.

Please make sure that:

- [Microsoft Visual C++ 2010 Redistributable Package (x64)](https://www.microsoft.com/en-us/download/details.aspx?id=14632) is installed
- [Java 8 64bit](https://java.com/en/download/windows_manual.jsp) is installed in place of Java 32bit

Another Windows user just resolved the issue by installing the VC++ Redist Package.

**Comment by orogvany** [comment]
Can close as resolved.

**Comment by cryptokat** [comment]
closed in favour of #853
