### ISSUE TITLE
The interface of the wallet software cannot be displayed!

### ISSUE THREAD

**Issue by sider123** [semuxproject/semux#515]
After Completing block data update,I created another  an new account, then ,I closed the wallet software.But when I opened  the wallet software again and entered  the password correctly,the interface
of the wallet software cannot be displayed，Unless I delete all the block data。
System information

Semux version: semux-windows-1.0.0-rc.5

OS & Version: Windows 7 x32

Expected behaviour

After the block data is updated,  restart the wallet software and  enter the correct password, the wallet interface should be displayed correctly.

Actual behaviour

After the block data is updated,  restart the wallet software and  enter the correct password, the wallet interface can't be displayed correctly.

Steps to reproduce the behaviour

1、Completing block data update;
2、Create a new account
3、restart the wallet software
4、enter the correct password.

My address: 0x0834c664d84c67187c9f14e853057e4b284036e6

**Comment by semuxproject** [comment]
Please re-open this ticket if this can be reproduced with semux v1.0.0
