### ISSUE TITLE
Peform Check if C++ redist is present on Windows 

### ISSUE THREAD

**Issue by mdodong** [semuxproject/semux#521]
#### System information

Semux version: v1.0.0

OS & Version:  Windows 10 64 bit

#### Expected behaviour

On Semux startup on windows a check should be done to see if  the c++ redist is installed and prompt for download if it is not yet installed

#### Actual behaviour

Semux will not launch and will not give any error message

#### Steps to reproduce the behaviour

1. Make sure  c++ redist is NOT installed on windows
2. Download Java
3. Download and run semux wallet

**Comment by semuxproject** [comment]
This has been implemented
