### ISSUE TITLE
Account balance isn't updated after a transaction

### ISSUE THREAD

**Issue by emi0912** [semuxproject/semux#522]
#### System information

Semux version: 1.0.0

OS & Version: Windows 7

#### Expected behaviour

After making a transfer of SEM from an account the balance needs to get updated in the account drop-list in the Send panel.

#### Actual behaviour

The balance is not updated in the drop-list in the Send panel. Only after adding/deleting an account in the Receive tab, the list gets updated.

#### Steps to reproduce the behaviour

1. Make a transaction and wait for it to get confirmed.
2. Go to the Send tab and check the balance of the address the transaction was send from.

0xd89eb50907cd9c557ca817f5b1b2a6c2e2be9d3f

**Comment by semuxproject** [comment]
Resolved by 77a768aa156607add2d515fc8466568aa67880e7
