### ISSUE TITLE
API feature request: get_transaction, get_account_transactions - Retrieve block number and/or block hash

### ISSUE THREAD

**Issue by bjguillot** [semuxproject/semux#525]
#### System information
Semux version: v1.0.0-4a83a2d
OS & Version: Linux/amd64

#### Expected behaviour
It would be nice if the get_transaction and get_account_transactions API calls would return the block hash and block number that the transaction was forged in.

#### Actual behaviour
These API calls only return the transaction hash (and other useful metadata).

Justification:

Being able to know the block number that a particular transaction was forged in will allow the development of software that is dependent upon the ordering of transactions. For example, validator pooling software needs to keep track of when addresses voted and unvoted.  By knowing the block number that these happened in, a timeline can be established to determine the correct payout for the validator pool.  Timestamps cannot be relied upon because of the possibility for time drift.

**Comment by cryptokat** [comment]
I am working on this.

**Comment by semuxproject** [comment]
This has been implemented
