### ISSUE TITLE
No error when entering wrong password on semux-cli

### ISSUE THREAD

**Issue by mdodong** [semuxproject/semux#532]
#### System information

Semux version: `v1.0.0`

OS & Version: `Ubuntu 16.04`

#### Expected behaviour

> semux-cli.sh
> enter password: 
> wrong password, try again
> enter password: 

#### Actual behaviour

> semux-cli.sh
> enter password: 
> 

it will exit to the console and will not indicated the wrong password
even on debug.txt doesn't show anything

#### Steps to reproduce the behaviour

1. Download and run semux on linux
2. create an account and set password
3. exit wallet
4. open wallet using cli 
5. enter wrong password

**Comment by cryptokat** [comment]
#539 addresses the issue of not showing error message

**Comment by semuxproject** [comment]
This has been fixed
