### ISSUE TITLE
Rename account button did not international

### ISSUE THREAD

**Issue by jezzmemo** [semuxproject/semux#533]
Hi there,

#### System information

Semux version: `v1.0.0`

OS & Version: `macOS 10.12.6`

#### Expected behaviour

I am a Chinese operating system, the software is displayed in Chinese

#### Actual behaviour

the rename button only show English 

#### Steps to reproduce the behaviour

1. Step one
Change your operating system to Chinese
2. Step two
![Rename account](https://raw.githubusercontent.com/jezzmemo/JJNetwork/master/tempImage/1516612755452.jpg)

**Comment by cryptokat** [comment]
Please update the translation here: https://crowdin.com/project/semux

**Comment by crimealone** [comment]
Already finished it.

**Comment by jezzmemo** [comment]
@crimealone duplicate bug?

**Comment by crimealone** [comment]
有一个平台专门翻译软件的

**Comment by semuxproject** [comment]
Thank you! will update all translations before release.
