### ISSUE TITLE
Wrong Behaviour Of Right Click -> Paste

### ISSUE THREAD

**Issue by cryptoll** [semuxproject/semux#538]
#### System information

Semux version: v1.0.0

OS & Version: Windows 10

#### Expected behaviour

When right clicking on a textbox (i.e the 'To' field in 'Send' screen) and choosing paste, the text should be pasted in that textbox.

#### Actual behaviour

If you don't left click on the textbox first, the text won't be pasted. Moreover, the text will actually be pasted in the last textbox the cursor was in (after left clicking on it). If you right click on a textbox and choose paste, before making a left click in any other textbox in the screen, the text won't be pasted at all.
Switching between screens resets the 'active textbox' so you have to left click on a textbox again before being able to paste.

#### Steps to reproduce the behaviour

1. Copy some text from another application.
2. Open a screen with an editable textbox (i.e 'Send').
3. Right after that, right click in one of the textboxes and choose paste (without left clicking on any other textbox before that).
4. Now, left click on that text box and then right click and paste.
5. Go to another textbox in the same screen and right click and paste.

If you find this helpful, this is my address for the bounty: 
0x2043d0f57c68e67e23a59e6a9c088a271c2448e5

**Comment by semuxproject** [comment]
fixed
