### ISSUE TITLE
Add numbering (# column like on Receive view) to  Delegates view

### ISSUE THREAD

**Issue by ocvaad** [semuxproject/semux#54]
It is impossible to tell what total amount of the delegates. 
Would be nice to have numbering on the Delegates view. 
Delegates view
![image](https://user-images.githubusercontent.com/32023262/31425027-188b5c84-ae66-11e7-90d8-1cce8bf51c87.png)
Receive view
![image](https://user-images.githubusercontent.com/32023262/31425081-6177e034-ae66-11e7-84cf-300a961da513.png)

**Comment by semuxproject** [comment]
implemented
