### ISSUE TITLE
API feature request: get_account - Return transactionCount data field

### ISSUE THREAD

**Issue by bjguillot** [semuxproject/semux#542]
#### System information
Semux version: v1.0.0-4a83a2d
OS & Version: Linux/amd64

#### Expected behaviour

It would be nice if the get_acount API calls would return a data field called "transactionCount" that allowed the user to know how many total transactions are available to be retrieved by the get_account_transactions API.  

For example, this would allow the user to do things such as request the last 5 transactions by calling get_account first, getting the transactionCount, and then supplying from=transactionCount-5 and to=transactionCount to get_account_transactions.

It would also generally prevent guesswork when trying to know how many transactions need to be paged through or read ahead of time.

#### Actual behaviour

Now, you must do things such as paginate through get_account_transactions by requesting 0,100 the 100,200 then 200,300, etc. until you get back an array less than 100 in size to know you hit the last entry.

[Discord user joyteq#3002]

**Comment by orogvany** [comment]
Seems like if this is the only usecase for getting total, that supporting end=-5 or other common paging techniques would be preferrable to double calls?

**Comment by cryptokat** [comment]
resolved by #543
