### ISSUE TITLE
The UI is wrong

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#547]
#### System information

Semux version:  v1.0.0-rc.1

OS & Version:  Windows 10

#### Expected behaviour

The “delegate” tab  show correct。

#### Actual behaviour

The “delegate” tab  show incorrect，can not see delegate list

#### Steps to reproduce the behaviour

1. rename account with string “111111111111111111111222222222222222222222222222222333333333333333333333aaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccc”
2. click “delegate” tab

#### Backtrace

````
[backtrace]
````

**Comment by cryptokat** [comment]
For reference
![selection_145](https://user-images.githubusercontent.com/32390172/35284752-8fb0a0b2-0096-11e8-859b-e965308523f6.png)

**Comment by likaigithub** [comment]
If you find this helpful, this is my address for the bounty:
0xf6e80170fc82e49b8a23a178a6c9e84b4d5fcb2f

**Comment by orogvany** [comment]
Can close as resolved from #865

**Comment by cryptokat** [comment]
resolved via #865
