### ISSUE TITLE
Transfer dropdown box does not display the balance

### ISSUE THREAD

**Issue by ji2318945** [semuxproject/semux#548]
System information

Semux version: semux-windows-1.0.0-4a83a2d

OS & Version: Windows 7

Commit hash : Transfer dropdown box does not display the balance
![image](https://user-images.githubusercontent.com/35736300/35285686-026405a2-0099-11e8-8188-f3389941aec6.png)
![image](https://user-images.githubusercontent.com/35736300/35285696-0b4ac7a0-0099-11e8-9400-e68632214147.png)

**Comment by ji2318945** [comment]
System information

Semux version: semux-windows-1.0.0-4a83a2d

OS & Version:  Windows 7

Commit hash : Transfer dropdown box does not display the balance
![image](https://user-images.githubusercontent.com/35736300/35285217-bfc63612-0097-11e8-8319-c57b3cb319b8.png)

![image](https://user-images.githubusercontent.com/35736300/35285246-d08ba842-0097-11e8-8886-9724e961205e.png)

**Comment by semuxdev** [comment]
Same as #522. Fix has been provided
