### ISSUE TITLE
Import and Export private key

### ISSUE THREAD

**Issue by mdodong** [semuxproject/semux#55]
Requesting to add feature to import and export using private key.

**Comment by cryptokat** [comment]
I will work on this once https://github.com/semuxproject/semux/issues/65 is done

**Comment by cryptokat** [comment]
`--exportprivatekey` implemented in https://github.com/semuxproject/semux/pull/208

**Comment by cryptokat** [comment]
`--importprivatekey` implemented in https://github.com/semuxproject/semux/pull/219
