### ISSUE TITLE
 The next transaction can be sent again after the transaction is lower than the previous transaction amount.

### ISSUE THREAD

**Issue by ji2318945** [semuxproject/semux#554]
System information
Semux version: v1.0.0

OS & Version: Windows 7 X64

 Expected behaviour

Update the correct value after the transaction is completed

 Actual behaviour
 The next transaction can be sent again after the transaction is lower than the previous transaction amount. Return to normal after 30 seconds。There is a lock on the use of other purses, and it doesn't happen.

Steps to reproduce the behaviour

1. Step one
![image](https://user-images.githubusercontent.com/35736300/35312449-73a116f8-00f6-11e8-8816-deb468fc517b.png)
![image](https://user-images.githubusercontent.com/35736300/35312458-81c5361a-00f6-11e8-8d9e-9361f6c820f7.png)

2. Step two
![image](https://user-images.githubusercontent.com/35736300/35312478-96c3871a-00f6-11e8-81d2-1f6df86bedea.png)
![image](https://user-images.githubusercontent.com/35736300/35312486-a4a451fc-00f6-11e8-8dfb-fa1e8f811011.png)

**Comment by cryptokat** [comment]
duplicate: #522
