### ISSUE TITLE
can not recover aliases from backup file

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#561]
Hi there,

#### System information

Semux version: v1.0.0-rc.1

OS & Version: Windows 10

#### Expected behaviour

recover aliases from backup file.

#### Actual behaviour

can not recover Aliases from another account

#### Steps to reproduce the behaviour

1. create a new account
2. recover from the backup file.
3. the address can revoce,but the aliases can not.

#### Backtrace

````
[backtrace]
````

If you find this helpful, this is my address for the bounty:
0xf6e80170fc82e49b8a23a178a6c9e84b4d5fcb2f

**Comment by cryptokat** [comment]
duplicate: #565
