### ISSUE TITLE
It will miss vote state after recover from a backup file.

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#564]
Hi there,

#### System information

Semux version: v1.0.0-rc.1

OS & Version: Windows 10

#### Expected behaviour

still show my vote state in new wallet.

#### Actual behaviour

the vote state is 0.

#### Steps to reproduce the behaviour

1. create a new account and recover from backup file which had voted some validators。
2. check “delegates”--->"my votes"

#### Backtrace

````
[backtrace]
````

If you find this helpful, this is my address for the bounty:
0xf6e80170fc82e49b8a23a178a6c9e84b4d5fcb2f

**Comment by phash** [comment]
All votes were reset on main net start. Please vote again

**Comment by likaigithub** [comment]
this is on main net alreadly。

**Comment by cryptokat** [comment]
This is expected because we didn't migrate delegates from RC net to 1.0.0 net.

**Comment by likaigithub** [comment]
Sorry，my english is poor.I mean i have two account,they both run 1.0.0 on mainnet.One of them had voted some validators . When i  use another account to recover the this account，the vote state can not revocer.

**Comment by cryptokat** [comment]
@likaigithub I don't think you can recover one account with another. Each account has its own private key.

**Comment by likaigithub** [comment]
sorry again，not account，i mean wallet，two wallet。
