### ISSUE TITLE
Recovery procedure doesn't restore a saved address book

### ISSUE THREAD

**Issue by blazer01** [semuxproject/semux#565]
#### System information
Semux/v1.0.0-4a83a2d/Windows/amd64

OS & Version: Windows 7x64

#### Expected behaviour
Wallet backup contains an address book. "Restore wallet" procedure recoveres the saved address book.

#### Actual behaviour
A wallet file stores an address book, but recovery procedure doesn't restore a saved address book.

#### Steps to reproduce the behaviour
Restore a wallet with an addressbook from a backup. The address book is empty (isn't recovered).

Bounty address is 0x9f0b3262b87d5350b81da69a8f79fd7893f9eff9

**Comment by orogvany** [comment]
This is expected/known issue, as testnet wallet did not contain address book.

**Comment by blazer01** [comment]
Disagreed. I've reproduced it in mainnet wallet. It 's obvious that mainnet wallet contains addressbook unlike testnet where it was stored in the separate json file.

**Comment by blazer01** [comment]
Once again to make it clear. The bug is reproduced with backup of mainnet wallet which contains addressbook. I don't use any old wallet from testnet.

**Comment by cryptokat** [comment]
@blazer01 Thanks for reporting this. I can confirm that the issue is reproducible with version 1.0 of the  wallet.

**Comment by orogvany** [comment]
fixing now.  Sorry for confusion

**Comment by blazer01** [comment]
Didn't get any bounty, again.
