### ISSUE TITLE
can not search Block infomation with "Blocks Explorer"

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#567]
Hi there,

#### System information

Semux version: v1.0.0-rc.1

OS & Version: Windows 10

#### Expected behaviour

show block infomation when i search with block's hash "0xc7f1e04f63fd92afac6c9f17ce89a4fc437512601042ec06759b65ce24829d66"

#### Actual behaviour

show noting

#### Steps to reproduce the behaviour

1. open wbesite (https://semux.info/explorer)   and search "0xc7f1e04f63fd92afac6c9f17ce89a4fc437512601042ec06759b65ce24829d66"
2. search

#### Backtrace

````
[backtrace]
````

If you find this helpful, this is my address for the bounty:
0xf6e80170fc82e49b8a23a178a6c9e84b4d5fcb2f

**Comment by cryptokat** [comment]
This is out of scope for the wallet software. Please contact the site owner of semux.info on Discord.
