### ISSUE TITLE
Delegates panel should show decimals for low values

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux#569]
If I vote say 0.6 SEM for a validator for whatever reason
the panel will say votes = 1

If i then go and try to unvote 1, it gives an error

similarly, if I vote 19.99, it will show 20, and I will be unable to unvote properly.

Also, this can lead to fractional SEM remaining locked, despite delegate votes all showing 0
It should always round down, or if <1, show the fractional remains
Or always show fractional numbers

**Comment by cryptokat** [comment]
closed by #681
