### ISSUE TITLE
no feedback on saving a Addressbook entry with no name 

### ISSUE THREAD

**Issue by phash** [semuxproject/semux#573]
#### System information

Semux version: `e.g., v1.0.0-rc.1`

OS & Version: `e.g., Windows 10, Mint 18.2

#### Expected behaviour

when adding an entry to the addressbook, you are asked to insert a name.
Expected: Check if the Name is actually a String and give a feedback, if the name is either already used or the entry is empty

#### Actual behaviour
You can enter an empty String and it is just not saved. No Feedback is given

Description, screenshot allowed

#### Steps to reproduce the behaviour

Open SendPanel
Open AddressBook
click "Add"
On the "Name" Input Dialog do not enter anything
click OK
Enter an Semux Address
click OK

**Comment by semuxdev** [comment]
Resolved
