### ISSUE TITLE
The Transaction panel should show more Decimals

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#578]
Hi there,

#### System information

Semux version: v1.0.0-rc.1

OS & Version:Windows 10

#### Expected behaviour

show 0.000000001 SEM 

#### Actual behaviour

show 0.000 SEM

Description, screenshot allowed

#### Steps to reproduce the behaviour

I voted a validator with 0.000000001 SEM，and you can check here
[http://semuxchain.info/transaction/0xf3cb00c915d700251ad596120ce1a12b4e8bcf1eb428ca5eccf49188726f3783](http://semuxchain.info/transaction/0xf3cb00c915d700251ad596120ce1a12b4e8bcf1eb428ca5eccf49188726f3783)

then i check transaction panel  ,the amount is 0.000 SEM
![_ 24yz p y_aj dlm1axm](https://user-images.githubusercontent.com/9426498/35372332-5252cc9c-01d4-11e8-81f6-d49b1a8e3b50.png)

#### Backtrace

And this is my address for the bounty:
0xf6e80170fc82e49b8a23a178a6c9e84b4d5fcb2f

**Comment by orogvany** [comment]
This can be closed.

**Comment by cryptokat** [comment]
duplicate: #608
