### ISSUE TITLE
wrong amount after vote/unvote/transaction

### ISSUE THREAD

**Issue by fox19891989** [semuxproject/semux#583]
After i voted or unvoted, jump to the send page, but the amount hasn't been changed.

Version:
semux-macos-1.0.0-4a83a2d
semux-linux-1.0.0-4a83a2d.tar.gz

Step:
1. vote or unvote or make transaction
2.go to the 'SEND' menu
3.all of the amount haven't been changed.
![bug_sem](https://user-images.githubusercontent.com/1921671/35419598-2d592d84-027c-11e8-8cb6-b5f151fdf5b8.png)

**Comment by fox19891989** [comment]
i think the windows version has the same bug.

**Comment by semuxdev** [comment]
Same as #522. Already fixed
