### ISSUE TITLE
JavaFX GUI implementation.

### ISSUE THREAD

**Issue by Vjeredy** [semuxproject/semux#586]
I'd like to make a JavaFX version of current GUI. Right now i'm still looking through current implementation to better understand how it can be improved or remade. If you are interested - will upload my work as soon as it is ready to show so we can continue further discussion.

**Comment by Vjeredy** [comment]
Here i've made first - home page, tell me if this is appropriate or you have any suggestions. If everything ok i will carry on. By the way, where can get those icons used in app?
[Semux.zip](https://github.com/semuxproject/semux/files/1667805/Semux.zip)

**Comment by cryptokat** [comment]
Hello @Vjeredy 
You can find the icons in the resource bundle here: https://github.com/semuxproject/semux/tree/master/src/main/resources/org/semux/gui

**Comment by Vjeredy** [comment]
Home, Send, Transactions pages so far.
[Semux.zip](https://github.com/semuxproject/semux/files/1670030/Semux.zip)

**Comment by Vjeredy** [comment]
Main scenes finished. Next to come dialogs and secondary windows.
[Semux.zip](https://github.com/semuxproject/semux/files/1674537/Semux.zip)

**Comment by Vjeredy** [comment]
Added secondary pop-up windows.
[Semux.zip](https://github.com/semuxproject/semux/files/1678925/Semux.zip)

**Comment by semuxdev** [comment]
Thank you @Vjeredy

Could you use Pull Request for this change?

**Comment by Vjeredy** [comment]
I will do dialog windows, next add all JavaDoc, then upload whole GUI skeleton at once and make a pull so we be able to fill it with existing and a bit refactored code.

**Comment by phash** [comment]
this could be a good entry point, to seperate GUI from logic and do all the logic things one layer deeper

**Comment by Vjeredy** [comment]
Added support for dialog windows. Estimate 1-2 days before upload new graphic engine.
[Semux.zip](https://github.com/semuxproject/semux/files/1685429/Semux.zip)

**Comment by Vjeredy** [comment]
Made a pull request, can close this.
#642 
Latest build:
[Semux.zip](https://github.com/semuxproject/semux/files/1692567/Semux.zip)
