### ISSUE TITLE
Allow delegating the delegate status to another address

### ISSUE THREAD

**Issue by Messier81z** [semuxproject/semux#587]
This is a security feature.

It would be much more secure to allow delegating the delegate status to avoid keeping private keys on a cloud VPS.

Scenario where:

1) Wallet A burns 1k SEM and becomes a delegate.
2) Wallet A delegates the delegate status to an address in wallet B
3) Wallet B is deployed on a VPS.

Wallet A can revoke the delegate status from B any time. Wallet A private keys are kept secure and never go to the VPS. An attacker stealing B private keys does not gain ownership over the delegate.

**Comment by AlexAltertrader** [comment]
:+1:

**Comment by ocvaad** [comment]
Any ideas regarding the block forge reward?
Should it be sent to A (original delegate) or stay on B (declared delegate) ?

**Comment by Messier81z** [comment]
I would go with sending block rewards to A (the original delegate).

**Comment by orogvany** [comment]
dupe #598

**Comment by orogvany** [comment]
can close as dupe #598 #635 or whichever we think is best to keep open.

**Comment by orogvany** [comment]
Tracked in #598
