### ISSUE TITLE
semux client closes if opened from another folder

### ISSUE THREAD

**Issue by romiferns** [semuxproject/semux#59]
![semux run file error](https://user-images.githubusercontent.com/32784591/31580665-80cc88e8-b174-11e7-8c9f-f47f3eb09a68.jpg)
Hi,

The semux client closes if I try to open it from a folder apart from C drive.  It doesn't even start if I try to run it as an administrator.  Request you to help resolve this issue as I like to organize to keep the semux client in a dedicated folder.  My Operating System is 64 bit windows 7.  I have installed Java SE 8 update 144 and the 2010 redistributable.

**Comment by semuxproject** [comment]
This is related to account permission. We may add permission check in the near future.
