### ISSUE TITLE
Several bugs and unexpected behaviour of the address book

### ISSUE THREAD

**Issue by kaar2** [semuxproject/semux#596]
Yesterday I did some testing with the address book and found some unexpected behaviour. It happens if an address in the address book has an empty name. This can be caused by either one of the following:
1. Adding an address to the address book with an empty name.
2. Changing the name of an address in the address book to an empty name.
3. Adding a name to one of the addresses in the Receive tab and then removing the name.

Once one of the above happens the client becomes buggy. I'll the describe the issues I found, although I'm pretty sure there are more:
1. If you simply add an address to the address book with an empty name, the address won't actually show up in the address book, but the name will indeed change. In the drop lists in both Send and Delegates tabs the address will no longer appear and instead there will be an empty string (screenshots attached below).
![1](https://user-images.githubusercontent.com/35411733/35473408-f6ce1186-0388-11e8-998a-740f6d396d90.png)
![2](https://user-images.githubusercontent.com/35411733/35473418-0c1f2566-0389-11e8-9867-d0583827d1c6.png)

2. If you change the name of an already existing address to the empty name, again the address book won't be updated (the address will appear there with the old name), but the new name will be updated everywhere else (screenshot attached below).
![3](https://user-images.githubusercontent.com/35411733/35473423-1a9d5ffe-0389-11e8-9f4a-78310ca48542.png)

3. If you name an address through the Receive tab and then later want to remove the name (so the address will appear in the drop lists instead of the name) the only way to do that is by going to the address book and removing the address. When I tried to simply enter an empty name in the Receive tab, I got the same behaviour as in issue no. 2.

Additional comments:
- ~~The issues above happened not only when entering an empty string as a name. I also tried, space, tab, CR, LF and others. The null character however doesn't cause any issues.~~
I wasn't able to reproduce this with other strings beside the empty string. I checked the code and indeed it does occur only with the empty string.
- This is not related to the issues above , but when clicking on the Delete button in the address book there is no pop-up with "Are you sure?" text like there is when deleting an address in the Receive tab. If you delete your own address there is no problem, but after deleting an address that is not in your wallet data file, there is no way to restore it if you don't know the address.
#### System information

Semux version: v1.0.0

OS & Version: Windows 7, x64

My address is: 0xe9187ad84de23dc0e4eebc8dfb8ed1dc60072e22

**Comment by phash** [comment]
I made a commit, which prevents empty names... there are more negatives than positives on having only named accounts

**Comment by kaar2** [comment]
Thanks for the comment, I must have missed this when I searched if this issue was already posted here. 
I assume you refer to #575. If you do then this won't solve this problem, as it is caused not only by empty or null strings (read the first comment under 'Additional comments').

Also, once this happens the address book won't open next time the client is launched (see #597). I think it's worth looking into it to make sure it isn't caused by other things.

**Comment by orogvany** [comment]
I can take a swing at fixing this and adding more testing around address book.

I'm thinking that

- Name should not be required
- Adding address with duplicate should not be allowed
- Trim any whitespace for consistent empty v set behavior

Thoughts appreciated

**Comment by kaar2** [comment]
@orogvany, I like your suggestions beside the last one. Why would white spaces cause any problem?
I read cryptoll's comment too and I agree that the current behaviour of the address book is a bit weird. Not sure if all he said should be implemented, but a button that allows to remove a name should definitely be added.

**Comment by orogvany** [comment]
Ah sorry, I mean trailing and leading whitespaces @kaar2 not all whitespace.  If you set a name to "    " this should be handled the same as "", as the user can't see the difference anyway on the screen.  The same would go for names of "foo" and "foo   ".  It allows for better handling later if we decide to not allow duplicated names and for better rendering in the UI

**Comment by orogvany** [comment]
This can be closed, it's no longer repro reproing in latest develop branch

**Comment by cryptokat** [comment]
see #629
