### ISSUE TITLE
Address book doesn't open (related to #596)

### ISSUE THREAD

**Issue by kaar2** [semuxproject/semux#597]
This happens after doing one of the steps described in #596. After leaving an address with a blank name in the address book and closing the client. The address book won't open next time the client is launched.

#### System information

Semux version: v1.0.0

OS & Version: Windows 7 x64

#### Expected behaviour

After doing one of the steps described in #596, so the address book contains an address with a blank name and closing the client, the address book should open next time the client is launched.

#### Actual behaviour

The address book doesn't open next time the client is launched. It's fixed if you change the name of the blank named address to another name. However, this can only be done from the Receive tab, so if the address is removed from the wallet, there is no way to fix it without modifying the data files. The problem seems to be in the wallet.data file, as I tried to replace the whole client folder with a new one and the problem persisted. Only when I removed the wallet.data file the problem was fixed.

#### Steps to reproduce the behaviour

1. Add an address to the address book with a blank name.
2. Close the client.
3. Relaunch the client and click on the Address Book button.
4. Move the wallet.data from the client folder, restart the client and click on the button again.

My address is: 0xe9187ad84de23dc0e4eebc8dfb8ed1dc60072e22

**Comment by semuxdev** [comment]
Same as #650
