### ISSUE TITLE
Number of validators bigger than max validators

### ISSUE THREAD

**Issue by cryptozero** [semuxproject/semux#60]
validators = 51 with 50 max validators

10/14 08:42:53 [cons] INFO SemuxSync - Sync manager stopped
10/14 08:42:53 [cons] INFO SemuxBFT - Entered new_height: height = 34303, # validators = 51
10/14 08:43:25 [cons] INFO SemuxSync - Sync manager started, best known block = 34303
10/14 08:43:25 [sync-mgr-92] INFO SemuxSync - Block [number = 34303, view = 0, hash = 2a78311e6c32ef1878053d5f7f29c681490699a2388bf2fe7b249770a6367771, # txs = 0, # votes = 48]

**Comment by semuxproject** [comment]
The max number of validators increases from 20 to 100 gradually.
