### ISSUE TITLE
API: /get_pending_transactions potentially broken in 35d211b (testnet)

### ISSUE THREAD

**Issue by bjguillot** [semuxproject/semux#603]
#### System information

Semux version: Semux/v1.0.0-35d211b/Linux/amd64
Commit hash : 35d211b

#### Expected behaviour

Request: http://localhost:5171/get_pending_transactions
Response: {"success":true,"result":[{"hash":"0x0b07a7b472503e7588d99feca6bcb782ca2d627e865d56fd1759bb7688faa055","type":"VOTE","from":"0x155044d1839049da474de9f91556f2f74c60dcbb","to":"0x1ac49b26294baed719099efe94adc1200bc0180e","value":4000000000,"fee":5000000,"nonce":4,"timestamp":1517177224916,"data":"0x"}]}

#### Actual behaviour

Request: http://localhost:5171/get_pending_transactions
Response: {"success":false,"message":"Failed to process your request: null"}

#### Steps to reproduce the behaviour

1. On testnet, create a transaction (such as sending a 1 SEM vote to a delegate) to ensure there is a pending transaction
2. Make the API request

#### Other information
Testnet does not appear to be forging blocks now, so I don't know if perhaps this error is related to that or not, but even with blocks not forging, I would not expect a failure message.

Earlier I was trying an earlier build from a few days ago, 50b83b0, and it was returning a failure code when no transactions were pending.  I updated with today's code earlier and it correctly returned there were no pending transactions ({"success":true,"result":[]}), but as soon as I added a new transaction, it seemed to break again.

My mainnet node is running the latest official code (not the develop branch), so I was unable  to test how the new code is acting on mainnet.

**Comment by cryptokat** [comment]
I have experienced the same issue.

**Comment by cryptokat** [comment]
fixed by #609
