### ISSUE TITLE
API: /create_account enhancement request: optional name parameter

### ISSUE THREAD

**Issue by bjguillot** [semuxproject/semux#604]
#### System information
Semux version: Semux version: Semux/v1.0.0-35d211b/Linux/amd64
Commit hash : 35d211b

#### Expected behaviour

Would be nice to pass an optional "name" request parameter to the /create_account API so that you could control the naming of accounts created in the Semux wallet.

#### Actual behaviour

Currently, when using the /create_account API, there are no request parameters, and a new account is creating in the wallet without a name.  To change the name, you can use the GUI's "Rename Account" button.

This is a low priority request.  I don't need it at the moment, but it seems like it could be useful to people that might be doing a lot of account automation in the future.

**Comment by cryptokat** [comment]
resolved by #614
