### ISSUE TITLE
The coinbase value is wrong

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#610]
Hi dev，

#### System information

Semux version: 1.0.0-4a83a2d

OS & Version:  Windows 10

#### Expected behaviour

coinbase value update after the block update.

#### Actual behaviour

coinbase value did not update.

#### Steps to reproduce the behaviour

1. check coinbase value.

#### Backtrace
FYI 

![47y8btl4r0k3t _zcsj2 2](https://user-images.githubusercontent.com/9426498/35555788-44061b52-05db-11e8-83b0-b040e68d7dbc.png)

And this is my address for the bounty:
0xf6e80170fc82e49b8a23a178a6c9e84b4d5fcb2f

**Comment by cryptokat** [comment]
The `Coinbase` on the home panel shows the coinbase of your own wallet.
