### ISSUE TITLE
the "unvote" transaction  should be disable.

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#613]
Hi dev,

#### System information

Semux version: 1.0.0-4a83a2d

OS & Version: Windows 10

#### Expected behaviour

unvote transaction is disable

#### Actual behaviour

still can do unvote transaction even your wallet do not have enough sem.

#### Steps to reproduce the behaviour

1. vote somebody use all your sem.
2. unvote this guy Immediately before next block synced。
3. you will find you can still unvote even you do not have enough sem.
4. this unvote transaction in "transaction record" always show "wait send".

#### Backtrace
FYI
![kfryb7c dw5lb7o ymeve n](https://user-images.githubusercontent.com/9426498/35559398-a85e0fd8-05e5-11e8-901a-b78031281240.png)

And this is my address for the bounty:
0xf6e80170fc82e49b8a23a178a6c9e84b4d5fcb2f

**Comment by cryptokat** [comment]
Hello @likaigithub 
What do you mean by `when you do not have enough sem.`?
If there isn't enough votes locked with the selected delegate, then the GUI should show you something like this:
![selection_172](https://user-images.githubusercontent.com/32390172/35559685-4e64b440-05e6-11e8-9497-7da30d13eb4f.png)

**Comment by likaigithub** [comment]
I mean enough sem in wallet to do unvote ,for example, I have 2 sem in my wallet，I vote validator 1.994 sem，then i unvote Immediately ，the unvote should be disable because the fee is 0.005 and my wallet only has 0.001 sem，but it can unvote。（The validator which i had vote 100 sem before this operating ,so it locked 100 sem already）

**Comment by likaigithub** [comment]
after 40 m，it still "wait send"
![fzr0 e ur8l fdbf 2 gmi](https://user-images.githubusercontent.com/9426498/35560784-53acb86e-05e9-11e8-86db-bd56600f711b.png)

**Comment by semuxdev** [comment]
It's because the GUI is using delegatestate instead of pending state.

**Comment by cryptokat** [comment]
I wasn't able to reproduce the issue. The GUI shows an error `INSUFFICIENT_LOCKED` from the TransactionExecutor

**Comment by cryptokat** [comment]
might be duplicated: #580

**Comment by likaigithub** [comment]
I can not reproduce this  either.
