### ISSUE TITLE
UI language

### ISSUE THREAD

**Issue by wzcbjfu** [semuxproject/semux#616]
Hallo,

It would be better to let user to choose the UI language by themselves. For instance, I am using Chinese UI Windows 10. I cannot use the English UI of Semux. No way to set.

Thank you
0x27056dc1fa1b35f84e556c1c65941cc8e6b1bfac

**Comment by cryptokat** [comment]
Hello @wzcbjfu 
You can change the language of UI by adding this line to `config\semux.properties`:

```
ui.locale = zn_CN
```
