### ISSUE TITLE
Allow double click from Address Book to auto complete Send address

### ISSUE THREAD

**Issue by GMule2k** [semuxproject/semux#619]
Enhancement request:
Slightly related to #https://github.com/semuxproject/semux/issues/479

Allow you to double click an Address Book entry to complete the Send To address in the Send tab.

That is: When you want to Send an amount of SEM, click on Address book button to open the address book, double clicking an existing entry from there would auto complete the Send to address in the Send tab.  (ideally also showing the Nickname in the Send page).

**Comment by orogvany** [comment]
I think #479 would cover this need better.  A dropdown for addresses in address book would be a better experience than going through addressbook for selecting addresses.

**Comment by orogvany** [comment]
I think we can close in favor of #479

**Comment by orogvany** [comment]
#479 covers this case
