### ISSUE TITLE
Add more DNS lookup servers

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux#624]
DNS lookup for seed peers at startup has a few problems that should be addressed.

For a truly fault tolerant distributed system, there should not be single points of failure.

Currently, new clients cannot join the cluster if the DNS seed is down or attacked.  We should get some failover/secondary dns peer resolution servers up.  Likely this should be in the configuration, so we do not have to release new code in times of crisis, or as new ones are added.

I would imagine that semux.info, semuxchain.info, etc could host backup DNS resolution, preferrably pointing at a variety of known validators.

The code also assumes that the port will always be default, which is not the case.

**Comment by cryptokat** [comment]
for reference: https://github.com/sipa/bitcoin-seeder

**Comment by phash** [comment]
is there a "list of things exchanges want"? - there are tons of shitcoins listed on major exchanges... don't think they are that well worked out, too

**Comment by semuxdev** [comment]
Agreed. Any actively maintained DNS seed servers are welcomed.

**Comment by orogvany** [comment]
Client now supports additional seeds.  So the feature part of this can be closed out.
However, we should actually have another DNS seed setup before acceptance

**Comment by cryptokat** [comment]
Added an alternative DNS seed in #662
