### ISSUE TITLE
when your delete an account,the address book still hold it

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#629]
Hi dev,

#### System information

Semux version: windows-1.0.0-4a83a2d

OS & Version: Windows 10

#### Expected behaviour

after you delete an account,the address book should update.

#### Actual behaviour

The address book does not update.

#### Steps to reproduce the behaviour

When you rename an account，the account will show in address book automaticlly.
But after you delete an account which had been renamed,the address book still have the account and it's 
alias.Is that ok?

If you find this helpful, this is my address for the bounty:
0xf6e80170fc82e49b8a23a178a6c9e84b4d5fcb2f

**Comment by likaigithub** [comment]
Also ，if i delete an account from address book，it's not just remove the account from address book,the accout's alias will be delete too.

**Comment by cryptokat** [comment]
resolved by #630

**Comment by cryptoll** [comment]
In my opinion this is the way it should work. You should have the option to have addresses in the address book which are not in your wallet.data and vice versa. The only thing that needs to be fixed imo is the naming mechanism, as it is not very intuitive right now and also pretty buggy (see #596 and #597). I suggest making the following changes:

1. Adding an option to remove an address name. In the Receive tab I suggest adding a 'remove name' button to the dialog box that pops up when you click on rename account.
2. An edit button should be added to the address book to allow modification of names. Again a 'remove name' button should be added to the edit dialog box which will allow keeping addresses in the address book without names.
3. Removing an address from the address book should not have any effect on the name of the address as it appears in the Receive tab.
4. This is not a change actually rather I suggest preserving the current behaviour. Like I said, removing an address from the wallet data should not remove it from the address book, nor remove it's name.

**Comment by orogvany** [comment]
with latest develop,
1 is fixed.  You can remove the name from address book, and the address will remain in your account, just sans name.
2) Edit button was added already
3) With the way the current feature has been implemented, this wouldn't fit the design.
4) This is how it currently functions

So this should be able to be closed.

**Comment by cryptokat** [comment]
Confirmed to be fixed
