### ISSUE TITLE
Client won't run on VPS - missing space in batch file

### ISSUE THREAD

**Issue by ocvaad** [semuxproject/semux#63]
Client won't start on VPS (Win10X64 admin user) due to missing space in batch file. 
There is a difference in file output for Notepad and Notepad++ view. 
Probably related to editor software that used to save batch file. 

On PC (Win10X64 admin user) batch executed normally. 

![image](https://user-images.githubusercontent.com/32023262/31582179-c9b71b2a-b185-11e7-91ed-3e31e713f01f.png)

![image](https://user-images.githubusercontent.com/32023262/31582183-de9fbfba-b185-11e7-81a8-9eb49bfaa46e.png)

**Comment by semuxproject** [comment]
This is because different platforms use different line character:
`\n` - by Linux and macOS
`\r\n` - by Windows

In future release, we should consider replacing `\n` with `\r\n`.
