### ISSUE TITLE
It's a small problem

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#632]
Hi dev,

#### System information

Semux version: v1.0.0

OS & Version: Windows 10

#### Expected behaviour

FYI
![ly b74ctfitzh 9 q1_o f](https://user-images.githubusercontent.com/9426498/35727200-4f3a2e32-0842-11e8-9ab9-d2b0a35c0e6d.png)

**Comment by cryptokat** [comment]
resolved by #633
