### ISSUE TITLE
Add a feature that allows for renting of a delegate

### ISSUE THREAD

**Issue by Messier81z** [semuxproject/semux#635]
Add a feature that allows for renting of a delegate. It's similar to https://github.com/semuxproject/semux/issues/587 but allows address B to collect block rewards for N number of blocks (specified in the "rent" tx) 

The actual usefulness of this idea is up for a discussion :)

**Comment by orogvany** [comment]
So.. ok.. I've blown the 1000 sem to register delegate, and now I don't have votes to control.  What good is it for the network to be able to rent this to someone else who controls the vote?

**Comment by orogvany** [comment]
dupe #598 
Folks would have to figure out fees between them, rather than as part of official behavior.

**Comment by orogvany** [comment]
Tracked in #598
