### ISSUE TITLE
Add Java 9 Support 

### ISSUE THREAD

**Issue by semuxdev** [semuxproject/semux#639]
**Motivation**
Java 9 comes with a bunch of new features and enhancements. It also solves the HiDPI issue #637 

**Proposal**
Investigate the compatibility with Java 9. Consider bumping the minimum required JRE version.

**Comment by bjguillot** [comment]
Is this just to test the codebase for Java 9 compatibility, or is this to move the minimum required JRE to Java 9?

**Comment by semuxdev** [comment]
I am assuming the current codebase is compatible with Java 9. Mainly wanted people to use Java SE 9 for better GUI experience.

**Comment by orogvany** [comment]
I would hazard to say that requiring java9 might be a bit too early.  but I do support being bleeding edge.  I just don't see the  benefit as of right now

**Comment by semuxdev** [comment]
Thank you @bjguillot for the feedback. I think it's more appropriate to call it add java 9 support.

**Comment by cryptokat** [comment]
@semuxdev Shall we merge #674 as well for 1.0.1 to address the warning of reflection in Java 9?

**Comment by cryptokat** [comment]
#674 #684
