### ISSUE TITLE
If i delete two accounts in my wallet，then the transaction records between the two accounts will be delete from my wallet.

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#643]
Hi dev,

#### System information

Semux version:v1.0.0

OS & Version: Windows 10

#### Expected behaviour

still keep all the transactions in my wallet.

#### Actual behaviour

the transaction records will be deleted too.

#### Steps to reproduce the behaviour

1. send sem form my account to another account in my own wallet.
2. delete these two accouts.
3.check transaction record.

If you find this helpful, this is my address for the bounty:
0xf6e80170fc82e49b8a23a178a6c9e84b4d5fcb2f

**Comment by cryptokat** [comment]
The wallet shows transactions only of the accounts in current wallet.data
