### ISSUE TITLE
Refactor CLI

### ISSUE THREAD

**Issue by cryptokat** [semuxproject/semux#65]
- [x] pick a library 
  - https://commons.apache.org/proper/commons-cli/
- [x] implement the refactor
  - [x] help
  - [x] version
  - [x] datadir
  - [x] account
    - [x] create
    - [x] list
  - [x] coinbase
  - [x] password
  - [x] changepassword
- [x] add test cases

**Comment by semuxproject** [comment]
Both libraries look good to me. If possible, I would suggest the commons cli because it's more often used by maven artifacts, https://mvnrepository.com/artifact/commons-cli/commons-cli
