### ISSUE TITLE
Winning strategy in Semux for block generation.

### ISSUE THREAD

**Issue by AlexAltertrader** [semuxproject/semux#652]
I think that the winning strategy in Semux is to change the position of the validator in the lists right after the block is generated, is not it?
Perhaps I am wrong, but I suspect that the algorithm for selecting a new validator for generation does not have a state.
So, every new choice occurs without calculation of the available statistics of block generation by each validator.

**Comment by orogvany** [comment]
It does have state currently.  Theres a long thread about this.  Lets keep the conversation centralized.  Thanks

**Comment by cryptokat** [comment]
See: #98 #462
