### ISSUE TITLE
0 sem can be send

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#656]
Hi dev,

#### System information

Semux version:  v1.0.0

OS & Version: Windows 10`

#### Expected behaviour

0 sem trnsaction should be banned.

#### Actual behaviour

0 sem send.

#### Steps to reproduce the behaviour

1. I vote for a pool 0.478 sem.
2. I get reword 0 sem.
3. check this 0xba58bd67fb2a1874429bda01d6235cb1de7c5c75ac9e75068e27a2a107a1b675    and
      0xc7996a0373f6b5991e92e5614ac795e84da0253759c0396833df626558054e16

I think this is a bug in api.

**Comment by cryptokat** [comment]
This is by design. In the future we will have contract create & call transactions which will also have a value of 0 sem.
