### ISSUE TITLE
Address alias length is unlimited

### ISSUE THREAD

**Issue by kaar2** [semuxproject/semux#659]
#### System information

Semux version: 1.0.0

OS & Version: Windows 7 x64

#### Expected behaviour

Address alias length should be limited to prevent OOM errors.

#### Actual behaviour

The length of address alias is unlimited. 

#### Steps to reproduce the behaviour

1. Add a new entry to the address book.
2. Choose a very long name (was able to to enter a name with ~100 million characters).

**Comment by orogvany** [comment]
This can be closed.
