### ISSUE TITLE
After the data are synchronized, different computers use the same wallet in the wrong amount.

### ISSUE THREAD

**Issue by martinisem** [semuxproject/semux#667]
System information
Semux version: semux-windows-1.0.0-4a83a2d

OS & Version:  Windows 7

Expected behaviour
After the data are synchronized, different computers use the same wallet in the same amount.

Actual behaviour
Data synchronization has completed 100% , the amount of the same wallet used by different computers is wrong.

Steps to reproduce the behaviour
![image](https://user-images.githubusercontent.com/36463338/36185898-a45cbef6-1176-11e8-81bf-b8e0a96ef4f1.png)

![image](https://user-images.githubusercontent.com/36463338/36185889-991fd190-1176-11e8-9387-a03138995044.png)

**Comment by cryptokat** [comment]
could be related to #522
