### ISSUE TITLE
Cancel the vote and prepare the transfer, the account amount is wrong

### ISSUE THREAD

**Issue by martinisem** [semuxproject/semux#669]
Hi dev,

System information

Semux version: windows-1.0.0-4a83a2d

OS & Version: Windows 7

Expected behaviour

When a vote is cancelled to prepare a transfer transaction, the amount of the account should be in 
correct amount.

Actual behaviour

Cancel the vote and prepare the transfer, the account amount is wrong

Steps to reproduce the behaviour
1.Cancel the vote
![image](https://user-images.githubusercontent.com/36463338/36342733-8034f402-143d-11e8-91d0-d28cea4c6182.png)
2.My transfer record
![image](https://user-images.githubusercontent.com/36463338/36342693-e05857a8-143c-11e8-823a-03c136249e0d.png)
3.send sem
![image](https://user-images.githubusercontent.com/36463338/36342703-168bca08-143d-11e8-9fe0-4a9d510fb24b.png)

the account amount  is wrong!

**Comment by cryptokat** [comment]
this is a duplicate with #522
