### ISSUE TITLE
Whales can receive more awards for forged blocks

### ISSUE THREAD

**Issue by telllic** [semuxproject/semux#670]
**Steps to reproduce the behaviour**

1. I have 40,000 SEM
2. I register as a delegate and VOTE for myself with all my coins.
3. After a few blocks (< 200 blocks) I become a validator.

4. Right now I can UNVOTE all my votes and VOTE for one or more pools. At the same time, I have status a validator and I forge blocks.
5. After ~196 blocks, I UNVOTE all my votes from pools and VOTE for myself again. Thus I get to  top-100 and confirm status a validator.
6. Now I can UNVOTE all my votes and VOTE for one or more pools again.
7. This I will do cycle every 200 blocks.

**Solutions**
1. Make a minimum gap between VOTE / UNVOTE 200 blocks.
2. Or make minimum stake age votes 200 blocks for pools (@orognvany). Votes for validators/delegates should only be counted after it stayed for at least 200 blocks.

**Comment by honeycrypto** [comment]
Yes, we were discussing minimal maturity time also in previous issues. Many community members agree that there should be a lock period between vote/unvote even longer: 2880 blocks or even 7 days.

**Comment by AlexSemuxTrader** [comment]
Thanks for the idea!
Now let's try :D

**Comment by telllic** [comment]
I think this is just as serious a bug as #620 and requires an urgent fix, but #611 you can discuss for a very long time...

**Comment by orogvany** [comment]
This is more a bug in the way pools calculate rather than a bug in semux itself.  I agree that making votes only count after 200 blocks is probably the easiest way forward.  I'll work on a fix for my pool software

**Comment by orogvany** [comment]
Fixed in my pool software in release 1.3
https://github.com/orogvany/semux-pool/releases/tag/1.3

Thanks for letting me know!

**Comment by cryptokat** [comment]
fixed by semux-pool in https://github.com/orogvany/semux-pool/releases/tag/1.3, see #611 for further discussion
