### ISSUE TITLE
Align with Oracle Java SE support roadmap

### ISSUE THREAD

**Issue by semuxdev** [semuxproject/semux#688]
Oracle recently updated their Java SE support roadmap. There will be two types of Java SE releases in the future, LTS and non-LTS versions with different support period.

It's better for us to align our Java strategy with this change. What is in my mind is that we should use LTS releases, e.g. Java 8/11, as main supported version, while keeps adding support for newer short term releases.

Reference: http://www.oracle.com/technetwork/java/eol-135779.html

**Comment by cryptokat** [comment]
closed by #693
