### ISSUE TITLE
When opening 2 clients one of them freeze with no error

### ISSUE THREAD

**Issue by cryptozero** [semuxproject/semux#69]
- Client running in one container
- New client with same wallet running on other container, ask for password and start, sync doesn't start, no error.

Closing the first container and restarting the second one fix the problem. If first container is restarted after starting the second one same problem occurs.

If it is expected behavior a message should warn other client is connected to the network.

SEM can't be transfered from gui wallet with other node running elsewhere with that wallet.

Workaround: creating a second address and selecting second account to start gui client.
```
10/15 23:18:40 [main] INFO Config - Semux v1.0.0-beta.4
10/15 23:18:40 [main] INFO Config - System booting up: network = 0, coinbase = xxxxxxxxx
10/15 23:18:41 [main] INFO Config - Latest block number = 0
10/15 23:18:42 [main] INFO NodeManager - Node manager started
10/15 23:18:42 [cons] INFO SemuxBFT - Consensus started
10/15 23:18:42 [cons] INFO SemuxBFT - Entered new_height: height = 1, # validators = 4
10/15 23:18:42 [p2p] INFO PeerServer - Starting peer server: address = 0.0.0.0:5161
```
nothing after this for several minutes

**Comment by semuxproject** [comment]
Multiple validators from the same machine is not allowed by the network. It will make the network more vulnerable to potential attack and should be prohibited in the future by community effort.
