### ISSUE TITLE
Visual C++ Redistributable for Visual Studio 2012 was not found.

### ISSUE THREAD

**Issue by AlexSemuxTrader** [semuxproject/semux#700]
#### System information
Semux version: semux-windows-1.0.1-27d00eb
OS & Version:  Windows 7
![image](https://user-images.githubusercontent.com/35813186/37041005-2f24b05c-216c-11e8-89bf-db27e71f0e38.png)

![image](https://user-images.githubusercontent.com/35813186/37041079-5afa1276-216c-11e8-93c2-a6a7e213972b.png)

**Comment by cryptokat** [comment]
Hi @AlexSemuxTrader 

Could you run these 2 commands in your cmd.exe then post the results here?

```
reg query HKLM\SOFTWARE\Microsoft\VisualStudio\11.0\VC\Runtimes\x86
```

```
reg query HKLM\SOFTWARE\Microsoft\VisualStudio\11.0\VC\Runtimes\x64
```

**Comment by AlexSemuxTrader** [comment]
![image](https://user-images.githubusercontent.com/35813186/37043209-2211e754-2171-11e8-9730-4db7b5dfa299.png)

**Comment by AlexSemuxTrader** [comment]
Reg paths was not found for both cases.

**Comment by cryptokat** [comment]
@AlexSemuxTrader 
There should be `VisualStudio\11.0` there if this package is installed: https://www.microsoft.com/en-us/download/details.aspx?id=30679

**Comment by AlexSemuxTrader** [comment]
Above the screen with the installed package. I reinstalled it (if you pay attention to the date), but it did not help.

**Comment by AlexSemuxTrader** [comment]
Issue was solved after reboot.

**Comment by cryptokat** [comment]
@AlexSemuxTrader Thanks for the update! I just added a reboot instruction in v1.0.1 release note.
