### ISSUE TITLE
[improvement] Testnet to not limit blocks to 1MB

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux#706]
For performance tweaking, it would be valuable if testnet would not limit block size to 1mb (~5k transactions).

I feel like we're eventually going to want to be able to support more transactions per block for higher throughput, so being able to see bottlenecks on the testnet and vet improvements there seems valuable.

Note: This limitation should remain in place on mainnet, only advise updating testnet to allow for pushing boundaries.  This will break consensus on testnet if we don't get validators to update, but I'm hoping we can just arrange for it, rather than forcing a fork.  Thoughts?

**Comment by orogvany** [comment]
This can be closed.

**Comment by cryptokat** [comment]
resolved by #725
