### ISSUE TITLE
"About" info and semux.bat start

### ISSUE THREAD

**Issue by KiparisD** [semuxproject/semux#71]
Hi there, i found a little bug in last beta - it still show 1.0.0-beta.3 in "About" tab in GUI and config! )))
![untitled](https://user-images.githubusercontent.com/32848096/31625571-247e477a-b2af-11e7-96ac-97656e610c01.png)

**Comment by semuxproject** [comment]
Confirmed: the terminal displays the correct version info after clean installation.
