### ISSUE TITLE
On Windows 10 64 bits, I'm asked to install Microsoft Visual c++ 2012 (or whatever the exact name) even if it's already installed

### ISSUE THREAD

**Issue by mathieuarbezhermoso** [semuxproject/semux#714]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the Discord channel here: https://discord.gg/qQVckKZ

#### System information

Laptop Nvidia + Intel

Semux version: `e.g., v1.0.0-rc.1`

1.01

OS & Version: `e.g., Windows 7, Ubuntu 16.04, macOS 10.12.6`

Windows 10 64 

Commit hash : `git rev-parse HEAD` (optional)

#### Expected behaviour

The wallet should start.

Description

#### Actual behaviour

The wallet doesn't start and give an error "please install Microsoft Visual c++ 2012"

Description, screenshot allowed

#### Steps to reproduce the behaviour

1. Step one
2. Step two

#### Backtrace

````
[backtrace]
````

**Comment by iiqqrs** [comment]
Post the debug file, we don't get any valuable information from just this.

**Comment by cryptokat** [comment]
Hi @mathieuarbezhermoso
Could you run these 2 commands in your cmd.exe then post the results here?

```
reg query HKLM\SOFTWARE\Microsoft\VisualStudio\11.0\VC\Runtimes\x86
```

```
reg query HKLM\SOFTWARE\Microsoft\VisualStudio\11.0\VC\Runtimes\x64
```

**Comment by cryptokat** [comment]
related: #700

**Comment by mathieuarbezhermoso** [comment]
It says the system didn't found the regkey. I just reinstalled again, same thing. I'll try to reboot tomorrow and see if it solve it as it did for #700

**Comment by cryptokat** [comment]
@mathieuarbezhermoso Please reopen this issue if reboot doesn't solve your problem.
