### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION 

### ISSUE THREAD

**Issue by borderline23** [semuxproject/semux#716]
When i can try to open a validator wallet on my personal pc.

JRE version: Java(TM) SE Runtime Environment (8.0_161-b12) (build 1.8.0_161-b12)
# Java VM: Java HotSpot(TM) Client VM (25.161-b12 mixed mode windows-x86 )
# Problematic frame:
# C  [leveldbjni-32-27d00eb-7305585592087917331.dll+0x2152e]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

#### System information

Semux version: `e.g., v1.0.1`

OS & Version: `e.g., Windows 10 64, 

1. Stop validator on vps
2. copy validator wallet.dat  on personal pc
3. open wallet

[hs_err_pid1332.log](https://github.com/semuxproject/semux/files/1799186/hs_err_pid1332.log)

**Comment by cryptokat** [comment]
Hi @borderline23 
Could you upload your debug.log also?
related to #649

**Comment by borderline23** [comment]
https://pastebin.com/a2gM82Qn
but nothing write in debug.log  chech creation time for the first

**Comment by borderline23** [comment]
https://pastebin.com/aVq5gWKL

java version
build 1.8.0_161-b12 on windows 10 x64

**Comment by cryptokat** [comment]
@borderline23 
It appears that you are using 32-bit version of Java.
Could you try to replace your Java with 64-bit version then see if the issue persists?
http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by borderline23** [comment]
work, so with validator wallet need 64bit java with normal user 32bit it's ok

**Comment by cryptokat** [comment]
This could also be related to UAC according to: https://www.java.com/en/download/help/exception_access.xml
Please reopen this issue if there's no provided way to resolve the error.
