### ISSUE TITLE
virus v4 

### ISSUE THREAD

**Issue by SHAADA** [semuxproject/semux#72]
v3 ok
https://www.virustotal.com/#/url/9559fd3a49a9d3757c1741d134cb213372253271754cff591ff37c8f62b3fd5f/detection

v4 virus
https://www.virustotal.com/#/url/4abc532b71e247e3e4b2f99972525614356aedfa0be74f53550dcd37d8300dd7/detection

**Comment by semuxproject** [comment]
OcVaad clarified that the binary is clean after unzipping and uploading the files to virustootal.com, which means it's a problem of the website.

As this report provides zero value to the development of semux, I'm closing it.
