### ISSUE TITLE
wallet cannot lauch

### ISSUE THREAD

**Issue by majorrp2** [semuxproject/semux#721]
#### System information

Semux version: ` v1.0.1

OS & Version: `Windows 7, 

Semux new version v1,0,1 cannot launch, it showing microsoft c++2012 Redistributable Package is not installed, after I install and restart computer i still cannot start the start the semux wallet. it show the same problem that microsoft c++2012 Redistributable Package is not installed

**Comment by cryptokat** [comment]
@majorrp2 
Could you run these 2 commands in your cmd.exe then post the results here?

```
reg query HKLM\SOFTWARE\Microsoft\VisualStudio\11.0\VC\Runtimes\x86
```

```
reg query HKLM\SOFTWARE\Microsoft\VisualStudio\11.0\VC\Runtimes\x64
```

**Comment by majorrp2** [comment]
IT show that the systems was unable to find the specify registry key or value

**Comment by cryptokat** [comment]
@majorrp2 
Could you install both x64 and x86 version of [VC++ Redist 2012 Update 4](https://www.microsoft.com/en-us/download/details.aspx?id=30679) then reboot and try again?

**Comment by cryptokat** [comment]
Also you should see something like this in regedit.exe this if the package was successfully installed:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\11.0\VC\Runtimes\x86`

![selection_329](https://user-images.githubusercontent.com/32390172/37255373-9bcb7d3a-2586-11e8-9db1-d4443e04e8be.png)

**Comment by majorrp2** [comment]
Problem solve thank you it can launch now
