### ISSUE TITLE
Cancel the vote major bug!

### ISSUE THREAD

**Issue by yeyizong** [semuxproject/semux#731]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the Discord channel here: https://discord.gg/qQVckKZ

#### System information

Semux version: `e.g., v1.0.0-rc.1`

OS & Version: `e.g., Windows 7, Ubuntu 16.04, macOS 10.12.6`

Commit hash : `git rev-parse HEAD` (optional)

#### Expected behaviour

Description

#### Actual behaviour

Description, screenshot allowed

#### Steps to reproduce the behaviour

1. Step one
2. Step two

#### Backtrace

I can't all cancel the balance when i cancel the vote, and I've met two times in a row. So every time a node is voted off, there is a loss.Please tell me how to solve it and give me some rewards. Thank you.

![1](https://user-images.githubusercontent.com/37393772/37445773-c4b047aa-2854-11e8-9165-c39201febffb.png)
![2](https://user-images.githubusercontent.com/37393772/37445775-c7d2028e-2854-11e8-9db8-ce7255789870.png)
![3](https://user-images.githubusercontent.com/37393772/37445811-f7f7aefa-2854-11e8-93f3-44f6ae198937.png)

````
[backtrace]
````

**Comment by orogvany** [comment]
Currently for votes we now render to 3 decimals
I think there's proposals to extend this further as well.

Thanks for the report, we should verify once the dust settles on current PRs
<img width="393" alt="screen shot 2018-03-14 at 10 39 06 pm" src="https://user-images.githubusercontent.com/24282143/37446095-8cdc0520-27d8-11e8-96f4-f68c345ba45f.png">

**Comment by yeyizong** [comment]
What do you mean, is it normal that you can't mean that you can't withdraw all the votes?

**Comment by yeyizong** [comment]
What do you mean, is it normal that i can't  withdraw all the votes?

**Comment by cryptokat** [comment]
@yeyizong Please upgrade your wallet to 1.0.1 in order to see all votes.
