### ISSUE TITLE
Transaction record time BUG

### ISSUE THREAD

**Issue by yeyizong** [semuxproject/semux#735]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the Discord channel here: https://discord.gg/qQVckKZ

#### System information

Semux version: `e.g., v1.0.0-rc.1`

OS & Version: `e.g., Windows 7, Ubuntu 16.04, macOS 10.12.6`

Commit hash : `git rev-parse HEAD` (optional)

#### Expected behaviour

Description

#### Actual behaviour

Description, screenshot allowed

#### Steps to reproduce the behaviour

1. Step one
2. Step two

#### Backtrace
The record time of the wallet transaction was BUG, and the system time was at 10 o'clock a.m. on March 16th. The transaction record showed a record of 12 o'clock. After that, the transaction record was 10 o'clock again
![1](https://user-images.githubusercontent.com/37393772/37501033-72e23894-2907-11e8-960f-2e975b040bda.png)
![2](https://user-images.githubusercontent.com/37393772/37501056-8cf39e80-2907-11e8-8062-6dcfa621d9ed.png)

````
[backtrace]
````

**Comment by orogvany** [comment]
Whats your offset from UTC?  If its 10hrs/2 hours +- might help us track down source of bug easier.

**Comment by cryptokat** [comment]
The time of a transaction is not guaranteed to be correct. There is a time drift of +- 2 hours allowed which can be observed when your system clock is not synced with NTP time servers.

**Comment by yeyizong** [comment]
The transaction record time is higher than the current block height, which is obviously an error.

**Comment by yeyizong** [comment]
![bug1](https://user-images.githubusercontent.com/37393772/38006177-9a86f6b4-3276-11e8-95ed-cf1a0ba7b246.png)
![bug](https://user-images.githubusercontent.com/37393772/38006178-9ad65754-3276-11e8-9976-4ebb440ad100.png)

**Comment by yeyizong** [comment]
The transaction time can not guarantee the correctness, and then what kind of block chain technology is also discussed
