### ISSUE TITLE
Crash after input password

### ISSUE THREAD

**Issue by sanyinchen** [semuxproject/semux#745]
/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=63604:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/tools.jar:/Users/yinchensan/IdeaProjects/semux/target/classes:/Users/yinchensan/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar:/Users/yinchensan/.m2/repository/io/swagger/swagger-annotations/1.5.18/swagger-annotations-1.5.18.jar:/Users/yinchensan/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/Users/yinchensan/.m2/repository/org/apache/logging/log4j/log4j-api/2.10.0/log4j-api-2.10.0.jar:/Users/yinchensan/.m2/repository/org/apache/logging/log4j/log4j-core/2.10.0/log4j-core-2.10.0.jar:/Users/yinchensan/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.10.0/log4j-slf4j-impl-2.10.0.jar:/Users/yinchensan/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.59/bcprov-jdk15on-1.59.jar:/Users/yinchensan/.m2/repository/org/ethereum/leveldbjni-all/1.18.3/leveldbjni-all-1.18.3.jar:/Users/yinchensan/.m2/repository/io/netty/netty-all/4.1.22.Final/netty-all-4.1.22.Final.jar:/Users/yinchensan/.m2/repository/org/xerial/snappy/snappy-java/1.1.7.1/snappy-java-1.1.7.1.jar:/Users/yinchensan/.m2/repository/com/github/oshi/oshi-core/3.4.4/oshi-core-3.4.4.jar:/Users/yinchensan/.m2/repository/net/java/dev/jna/jna-platform/4.5.0/jna-platform-4.5.0.jar:/Users/yinchensan/.m2/repository/net/java/dev/jna/jna/4.5.0/jna-4.5.0.jar:/Users/yinchensan/.m2/repository/org/threeten/threetenbp/1.3.6/threetenbp-1.3.6.jar:/Users/yinchensan/.m2/repository/org/apache/commons/commons-lang3/3.7/commons-lang3-3.7.jar:/Users/yinchensan/.m2/repository/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar:/Users/yinchensan/.m2/repository/commons-validator/commons-validator/1.6/commons-validator-1.6.jar:/Users/yinchensan/.m2/repository/commons-beanutils/commons-beanutils/1.9.2/commons-beanutils-1.9.2.jar:/Users/yinchensan/.m2/repository/commons-digester/commons-digester/1.8.1/commons-digester-1.8.1.jar:/Users/yinchensan/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/yinchensan/.m2/repository/commons-cli/commons-cli/1.4/commons-cli-1.4.jar:/Users/yinchensan/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.4/jackson-core-2.9.4.jar:/Users/yinchensan/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.4/jackson-databind-2.9.4.jar:/Users/yinchensan/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar:/Users/yinchensan/.m2/repository/net/i2p/crypto/eddsa/0.2.0/eddsa-0.2.0.jar:/Users/yinchensan/.m2/repository/com/google/zxing/core/3.3.2/core-3.3.2.jar:/Users/yinchensan/.m2/repository/org/bitlet/weupnp/0.1.4/weupnp-0.1.4.jar:/Users/yinchensan/.m2/repository/com/github/zafarkhaja/java-semver/0.9.0/java-semver-0.9.0.jar:/Users/yinchensan/.m2/repository/com/github/ben-manes/caffeine/caffeine/2.6.1/caffeine-2.6.1.jar org.semux.gui.SemuxGui
objc[11066]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java (0x1054ac4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1055304e0). One of the two will be used. Which one is undefined.
13:26:06.080 WARN     SystemUtil       Failed to read version.
13:26:06.086 INFO     Kernel           Semux/v1.0.1-unknown/macOS/x86_64
13:26:06.089 INFO     Kernel           System booting up: network = mainnet, networkVersion = 0, coinbase = 6a24e1b87e9c8d5e61c468a7714de0f6163c7927
13:26:06.524 INFO     Kernel           Computer: manufacturer = Apple Inc., model = MacBook Pro (MacBookPro13,2)
13:26:06.617 INFO     Kernel           OS: name = Apple macOS 10.13.2 (High Sierra) build 17C88
13:26:06.631 INFO     Kernel           CPU: processor = Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz, cores = 2 / 4
13:26:06.635 INFO     Kernel           Memory: total = 8192 MB, available = 2457 MB, swap total = 2048 MB, swap available = 1379 MB
13:26:06.794 INFO     Kernel           Disk: name = disk0, size = 477102 MB
13:26:06.794 INFO     Kernel           Disk: name = disk1, size = 476802 MB
13:26:06.794 INFO     Kernel           Disk: name = disk2, size = 1390 MB
13:26:06.847 INFO     Kernel           Network: name = awdl0, ip = []
13:26:06.847 INFO     Kernel           Network: name = en5, ip = []
13:26:06.847 INFO     Kernel           Network: name = en0, ip = [172.18.35.33]
13:26:06.847 INFO     Kernel           Java: version = 1.8.0_131, xmx = 1820 MB
13:26:10.133 ERROR    SemuxGui         Uncaught exception during kernel startup.
java.lang.IndexOutOfBoundsException: input [0, 0], require: [0 4]
	at org.semux.util.SimpleDecoder.require(SimpleDecoder.java:117) ~[classes/:?]
	at org.semux.util.SimpleDecoder.readInt(SimpleDecoder.java:52) ~[classes/:?]
	at org.semux.util.SimpleDecoder.readLong(SimpleDecoder.java:57) ~[classes/:?]
	at org.semux.core.BlockHeader.<init>(BlockHeader.java:89) ~[classes/:?]
	at org.semux.core.BlockHeader.fromBytes(BlockHeader.java:168) ~[classes/:?]
	at org.semux.core.Block.fromBytes(Block.java:410) ~[classes/:?]
	at org.semux.core.BlockchainImpl.getBlock(BlockchainImpl.java:167) ~[classes/:?]
	at org.semux.core.BlockchainImpl.<init>(BlockchainImpl.java:125) ~[classes/:?]
	at org.semux.Kernel.start(Kernel.java:124) ~[classes/:?]
	at org.semux.gui.SemuxGui.startKernelAndMain(SemuxGui.java:267) ~[classes/:?]
	at org.semux.gui.SemuxGui.setupCoinbase(SemuxGui.java:241) [classes/:?]
	at org.semux.gui.SemuxGui.showUnlock(SemuxGui.java:206) [classes/:?]
	at org.semux.gui.SemuxGui.start(SemuxGui.java:170) [classes/:?]
	at org.semux.gui.SemuxGui.main(SemuxGui.java:87) [classes/:?]

Process finished with exit code 255

**Comment by cryptokat** [comment]
@sanyinchen Could you delete your `database` folder then try again? It appears that your database is corrupted.

**Comment by sanyinchen** [comment]
yea, that's the reason . Thanks .
