### ISSUE TITLE
2 wallet started on one IP issue

### ISSUE THREAD

**Issue by busminer** [semuxproject/semux#76]
I have two wallets running on the same local network on different devices with one extrenal ip adress, when I start the first one in the command window, you see blocks, validators and other information about the network, when you start the second wallet on other device in the command window nothing is displayed, did some screenshots of this issue.

http://picua.org/img/2017-10/17/b9t0l8uvdk85ws4vlcfy7t5oq.png

http://picua.org/img/2017-10/17/cqvuster5bcqfn0743rf6x43g.png
![1](https://user-images.githubusercontent.com/32847122/31651221-78a2a0f2-b323-11e7-8551-b32cf3fb33a7.PNG)
![2](https://user-images.githubusercontent.com/32847122/31651222-78bfcf9c-b323-11e7-97ba-0c859d6648a6.PNG)

**Comment by semuxproject** [comment]
Running two validators on the same computer is not allowed.
