### ISSUE TITLE
Wallet not displaying correctly on high DPI system (windows)

### ISSUE THREAD

**Issue by lodyman93** [semuxproject/semux#769]
#### System information

Semux version: v1.0.1

OS & Version: Windows 10 x64

Resolution : 3840x2160

#### Expected behaviour

display wallet in readable font

#### Actual behavior

font is so small that it can't be read 
![semux_wallet](https://user-images.githubusercontent.com/4867519/38450922-e9eefbb0-3a2e-11e8-8770-58c2da69713f.png)

#### Steps to reproduce the behavior

Start the wallet 

#### Attempts that was made to fix the issue 

From compatibility settings of JAVA.exe :
- Setting to override DPI Scaling behavior for JAVA.exe  
- Changing Scaling performer from Application to System and System enhanced 

#### Suggested Solution 
auto detection of DPI automatically

**Comment by semuxdev** [comment]
Upgrade to Java 9+ should be able solve this

**Comment by lodyman93** [comment]
it's working now .. much Thanks
