### ISSUE TITLE
miss sync and peer state

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#775]
Hi there,

#### System information

Semux version: semux-windows-1.0.1-27d00eb

OS & Version: Windows 10

#### Actual behaviour

Description, screenshot allowed

#### Steps to reproduce the behaviour

![q _3gpui95oah rtcb 77j](https://user-images.githubusercontent.com/9426498/38485749-7a96db9e-3c0d-11e8-9d37-76370451c368.png)

[backtrace]
````

**Comment by cryptokat** [comment]
duplicate #711
