### ISSUE TITLE
Why there are 9 decimals？  

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#776]
Hi there,
Why there are 9 decimals？  
1 sat  = 0.00000001 sem？  only have 8 decimals，the wallet show 9 decimals

#### System information

Semux version:semux-windows-1.0.1-27d00eb

OS & Version:  Windows 10

![oawlp yttrjhys_e3e qw](https://user-images.githubusercontent.com/9426498/38486691-511f8542-3c10-11e8-9b44-fa85343db145.png)

**Comment by cryptokat** [comment]
The minimum unit of Semux is Nano Sem.
1 Sem = 10^9 Nano Sem
