### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#777]
Hi there,

#### System information

Semux version:semux-windows-1.0.1-27d00eb

OS & Version: Windows 10

![rtdbc7nld u tv 89t](https://user-images.githubusercontent.com/9426498/38491188-bd901252-3c1d-11e8-9975-617b56368466.png)

FYI,this is debug.log
[debug.log](https://github.com/semuxproject/semux/files/1889300/debug.log)

**Comment by cryptokat** [comment]
Hi @likaigithub 
Could you try the resolution in this page? http://support.pitneybowes.com/VFP06_KnowledgeWithSidebarTroubleshoot?id=kA280000000PEE1CAO&popup=false&lang=en_US

> open the registry editor and locate the registry subkey: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters and add a new entry :
> Value Name: MaxUserPort 
> Value Type: DWORD 
> Value data: 65534

**Comment by likaigithub** [comment]
Because it's not always happen,so I'm not sure the resolution works.But i can launch the wallet  after restart my computer.

**Comment by cryptokat** [comment]
@likaigithub Please reopen this issue if the provided solution doesn't work for you.
