### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by RighteousWrath** [semuxproject/semux#8]

**Comment by RighteousWrath** [comment]
http://i89.fastpic.ru/big/2017/0908/61/8cbbdded461ec9ac594942eac5c80a61.png
Can't connect and sync with network

**Comment by semuxproject** [comment]
Hi @RighteousWrath, could you try add seed nodes to your config file?

Edit ``config/semux.properties``
```
# Seed nodes, separated by comma
p2p.seedNodes = 45.79.68.226:5161,172.104.58.70:5161,88.80.187.200:5161,139.162.66.86:5161
```

**Comment by RighteousWrath** [comment]
Thanks, it works now!
