### ISSUE TITLE
Seriously excessive CPU useage

### ISSUE THREAD

**Issue by Peesus** [semuxproject/semux#804]
I am not sure if someone has noted this already but the Semux wallet causes a huge strain my CPU when I am syncing. 

I would not be able to tell you the exact reason it is causing this issue but I have attached a screen dump of my activity monitor. 

For reference information I am using an early 2015 Macbook Pro with High Sierra version 10.13 and a 3.1 GHz Intel Core i7 with 16 GB 1867 MHz DDR3 RAM. 

Hope this helps

<img width="1280" alt="screen shot 2018-04-11 at 14 19 01" src="https://user-images.githubusercontent.com/33229318/38776820-30ad9d74-4095-11e8-9708-4ad856a1af17.png">

**Comment by cryptokat** [comment]
@Peesus Could you try [v1.1](https://github.com/semuxproject/semux/releases/tag/v1.1.0) then see if the issue persists? We've introduced some performance enhancements in the latest version.

**Comment by cryptokat** [comment]
@Peesus Please reopen issue if the issue persists with v1.1
