### ISSUE TITLE
The Latest source code can not compile.

### ISSUE THREAD

**Issue by catchstom** [semuxproject/semux#805]
Hi dev,

#### System information

Semux version: 25bc531

OS & Version: win10

Commit hash : 25bc531

FYI

![qq 20180415204053](https://user-images.githubusercontent.com/38237936/38778528-6c54676a-40ed-11e8-89b3-596b774c8afd.png)

**Comment by cryptokat** [comment]
please run `mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V`
