### ISSUE TITLE
Show Balance everywhere

### ISSUE THREAD

**Issue by phash** [semuxproject/semux#81]
I find it disturbing not to see my Balance when looking at other screens than the Overview.
Just add Balance / Locked to the ButtonBar/MenuBar or WindowDecoration or whereever it is easy to see

**Comment by semuxproject** [comment]
This is not necessary in my view. Balances are displayed when you need it, like sending coins and voting delegates. Will listen to community inputs on this though.

**Comment by phash** [comment]
hmm if you want to send a transaction, maybe to an exchange, you have to go to "home" remember your balance, go to "send" and put it into the textfield.
Same for votes - I think it would be nice to know, how much balance there is, without changing tabs.
