### ISSUE TITLE
LevelDB Database Folders Should be Named With Ascii Characters

### ISSUE THREAD

**Issue by levyashin1** [semuxproject/semux#811]
Hello, i installed semux 1.1a today (i heard b is having problem upgrading database) still database upgrade didn't work and I am synchronizing again. Also, the problem seems to like causing with unicodes.

![2018-04-16_22-48-38](https://user-images.githubusercontent.com/33433070/38831847-5492d602-41c9-11e8-9f71-e492dc9978a5.png)

First one is the new database and the second one is the old one it should have upgraded.

Also, the Unicode problem seems to continue in folders.

![2018-04-16_22-57-26](https://user-images.githubusercontent.com/33433070/38831915-8ddb43ea-41c9-11e8-889b-5c4bbf691c33.png)

**Comment by cryptokat** [comment]
The standard directory structure in your database folder must be strictly followed without customized names like your case:
```
database
|- index
|- account
|- block
|- delegate
|- vote
```
Otherwise the upgrade is expected to fail.

**Comment by levyashin1** [comment]
I didn't customize anything. It is how semux made default.

**Comment by cryptokat** [comment]
@levyashin1 Could you share the localization of your operating system?

**Comment by levyashin1** [comment]
Windows 10 x64 - Turkish

**Comment by cryptokat** [comment]
verified on turkish windows 10

**Comment by cryptokat** [comment]
@levyashin1 this issue can be temporary solved by setting `ui.locale = en_US` in your `config\semux.properties` file

**Comment by cryptokat** [comment]
resolved by #812

**Comment by cryptokat** [comment]
@levyashin1 This issue has been resolved since [v1.1.1](https://github.com/semuxproject/semux/releases/tag/v1.1.1)
