### ISSUE TITLE
Semux wallet GUI should reflect internal validator positions within 200-block round

### ISSUE THREAD

**Issue by yottahash** [semuxproject/semux#816]
#### System information

Semux version: v1.1.0

OS & Version: Windows 7 & others

#### Expected behaviour

List of validators from 1-100 in the GUI's delegate panel should reflect the sequential order with which validators are forging blocks as per latest v1.1 release (round-robin), updating every 200 blocks to represent any primary selection order changes. 

Potential alternate approach is to add an additional column that displays a Validator's current internal position that is used for primary selection.

#### Actual behaviour

List of validators in the GUI reorders in realtime from block-to-block as votes are added or removed, which does not reflect any meaningful order as the blockchain's internal validator order is locked for each 200 block round.

#### Steps to reproduce the behaviour

1. Step one: download wallet
2. Step two: observe delegate panel and how Validator order updates between blocks, not reflecting the internal Validator order with which blocks are being forged.

#### Backtrace

````
[backtrace]
````

**Comment by yottahash** [comment]
If GUI list of Validators remains fixed as per internal Validator order, a counter in the same panel showing number of blocks left until the next round might also be worthwhile.

**Comment by witoldsz** [comment]
> List of validators from 1-100 in the GUI's delegate panel should reflect the sequential order with which validators are forging blocks as per latest v1.1 release (round-robin), updating every 200 blocks to represent any primary selection order changes.

Why is this the expected behavior? I would rather see the actual position, this gives me an overview of what is happening now, in contrast to what had happened previously. Or is this just me?

**Comment by yottahash** [comment]
"I would rather see the actual position"... exactly. The GUI does not reflect the actual internal blockchain position of Validators, which is locked for 200 blocks. There is no way to know the actual order of Validators by looking at the GUI, only what the next round's order might be. No big deal, but more the more transparency the better IMO.

**Comment by orogvany** [comment]
What usecase does the user need to know the internal state?  e.g. why would a voter care?

**Comment by orogvany** [comment]
Ok I buy that.  But I think we'd need additional behavior.  Some indication where the current forger is at would be a start.

**Comment by semuxdev** [comment]
How about adding consensus info table at the home panel:
- Current primary validator
- Next primary validator
- Number of YES/NO votes (if this is a validator)
