### ISSUE TITLE
My wallet can’t sync  

### ISSUE THREAD

**Issue by likaigithub** [semuxproject/semux#821]
Hi dev,

My  wallet can't sync

#### System information

Semux version: semux-windows-1.0.0-4a83a2d

OS & Version: win10

#### Expected behaviour

wallet can‘t sync。

FYI，

[debug.log](https://github.com/semuxproject/semux/files/1945387/debug.log)

**Comment by orogvany** [comment]
We are now on version 1.1.1.  Please try that version and report back :D  

This might be due to our compression of blocks, not sure when that was added though.

**Comment by semuxdev** [comment]
Closing this ticket due to insufficient data for further investigation.
