### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by semuxdev** [semuxproject/semux#826]
![screenshot from 2018-04-30 21-34-30](https://user-images.githubusercontent.com/35751971/39457884-dac9cc94-4cbe-11e8-8ceb-ac5254e64bbd.png)
![screenshot from 2018-04-30 21-36-17](https://user-images.githubusercontent.com/35751971/39457885-dad5cdfa-4cbe-11e8-88cb-e9ec5dc2063b.png)

**Comment by semuxdev** [comment]
Various issues were found by analyzing the heap dump:
- The logger holds 70k `VoteSet`, which in return refers 14m `Vote`;
- Massive `InetSocketAddress` objects are retained in `HashMap`, probably from our IP connection filter;
- `Optional` should not be used as fields, otherwise it consumes additional memory.

**Comment by cryptokat** [comment]
resolved via #827
