### ISSUE TITLE
semux wallet

### ISSUE THREAD

**Issue by angielec** [semuxproject/semux#828]
hi
I have a problem with my wallet, I can't open it. 
I have install the semux-windows-1.1.1
![sans titre](https://user-images.githubusercontent.com/35628038/39484696-da0b6e6c-4d76-11e8-9888-514cad626f02.png)

**Comment by cryptokat** [comment]
Could you attach your debug.log file and the localization of your Windows?

**Comment by angielec** [comment]
[debug.log](https://github.com/semuxproject/semux/files/1964640/debug.log)

**Comment by cryptokat** [comment]
@angielec Could you install [jre-8u171-windows-x64.exe](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html) then try again?

**Comment by angielec** [comment]
new error message :
![sans titre](https://user-images.githubusercontent.com/35628038/39486906-fb907c42-4d7d-11e8-9914-e15a1ddff941.png)

**Comment by cryptokat** [comment]
@angielec Please install [vcredist_x64.exe](https://www.microsoft.com/en-us/download/details.aspx?id=30679)

**Comment by cryptokat** [comment]
@angielec Delete the `database` folder then try again. It's likely your database is corrupted due to a crash. Also make sure there is at least 3 GB space available on your disk.

**Comment by angielec** [comment]
perfect, thanks a lot for your help ;)
