### ISSUE TITLE
API: incorrect "nonce" of GET /account when pending transaction

### ISSUE THREAD

**Issue by witoldsz** [semuxproject/semux#832]
When there is a pending transaction, the `GET` `/account` shows old `nonce` until transaction completes.

That would be helpful if:
- either the `GET` `/account` has `nonce` aligned with pending manager,
- or there was a dedicated endpoint to fetch `nonce`

As a workaround, the light client could just manage the nonce by itself in-between blocks, but it adds complexity (where to store it, what if it's web wallet and user refreshed page – keep it in local storage?… etc…)

**Comment by cryptokat** [comment]
Returning pending txs from `GET /account/transactions` as #834 requested could also solve this issue for light clients because the latest nonce can be retrieved by looking up the latest pending tx. For example Metamask implemented a [NonceTrakcer](https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/controllers/transactions/nonce-tracker.js) utilizing pending transactions.

**Comment by witoldsz** [comment]
I think it might be a little bit confusing if `GET` `/account` says: last nonce is `X` and then the last transaction from `GET` `/account/transactions` would say otherwise.

**Comment by cryptokat** [comment]
@witoldsz Yes, that's true. Adding a new API `/account/pending-transactions` can be more clear to users.

**Comment by witoldsz** [comment]
The problem with separated endpoints for completed transactions and pending transactions is that if you would like to view them like currently, in Semux Wallet, you have to fetch from two endpoints and merge results. This gets complicated when you add a pagination to this, because now you have to code it around.

On the other hand, maybe it would be better if GUI would separate these two, but still it is more work to do (another list with its own pagination?) than just a single endpoint with `from=X$to=X+100` parameters.

**Comment by witoldsz** [comment]
My humble advise: merge pending transactions with completed under one endpoint within one list and update the `GET` `/account` to take it into account on `nonce` and `transactionCount` fields.

Or we never ever present pending with completed on one view like this:
![image](https://user-images.githubusercontent.com/544581/39672175-7f43d156-5125-11e8-8762-2ae562a84ddf.png)

**Comment by cryptokat** [comment]
Considering the fact that not all pending txs will be finalized, including pending txs in `GET /account/transactions` API can be troublesome for server-side applications like block explorer as it will require multiple synchronization steps when there is an external database that provides aggregate information.

**Comment by witoldsz** [comment]
You are right, that could be a problem for block explorers. So, I can see two options: separate pending transactions everywhere (`/account-pending`, `/account/transactions-pending`) or maybe add an extra query parameter to `/account`. `/account/transactions`, etc… so they would wither ignore or be aware of pending stuff.

What do you think?

**Comment by cryptokat** [comment]
I still prefer the solution of adding an independent endpoint for getting pending transactions and leaving others as they are. 

Nonces should be managed by client-side considering we might want to support [transaction overwriting](https://ethereum.stackexchange.com/questions/9072/canceling-overwriting-a-pending-transaction-using-geth-json-rpc) in the future.

**Comment by witoldsz** [comment]
OK then, not a big problem. Will probably just merge these with completed and always fetch them all at once. In normal use – there should never be more than few (dozens?) of them anyway.

**Comment by cryptokat** [comment]
Cool! I will implement the endpoint for pending txs soon.

**Comment by witoldsz** [comment]
Well, actually there is `GET` `/v2.0.0/pending-transactions` already. I do not know how did I miss it.
Example response:
```
{
  "success": true,
  "message": null,
  "result": [
    {
      "blockNumber": "null",
      "hash": "0x9195ebeda879bbad6e29a359ca9ba673a551989aef66464c00aa03da66514aa2",
      "type": "TRANSFER",
      "from": "0xd6562866496d1c43ca2f433ee69f42663f99fa30",
      "to": "0x7acb178cfb49b84ae51f79987a8eda1c43b712b0",
      "value": "1000000000",
      "fee": "5000000",
      "nonce": "17",
      "timestamp": "1525615501930",
      "data": "0x"
    }
  ]
}
```
Looks like the `nonce` is always associated to the `from` address, does it not?
