### ISSUE TITLE
API: no endpoint to fetch all my votes

### ISSUE THREAD

**Issue by witoldsz** [semuxproject/semux#836]
The 
- `GET` `/v2.0.0/delegates` has `votes` as a number, but there is no data of who was voting.

Also, the 
- `GET` `/v2.0.0/account` has no info of votes. 

The only way to display the "Votes from Me" column in "Delegates" section, using API, is to query 
- `GET` `/v2.0.0/votes?delegate=X` for each delegate, one by one. That is 130 requests on mainnet.

**Comment by witoldsz** [comment]
> I agree it could be made easier, but its doable now with only a few lines of code and one call on client side

Having accounts with thousands of transactions, fetching them all just to count the votes could kill server or client.

**Comment by semuxdev** [comment]
Fixed
