### ISSUE TITLE
API: optional password for "safe" endpoints?

### ISSUE THREAD

**Issue by witoldsz** [semuxproject/semux#846]
Most of the endpoints are "safe" to be used without any password as they are just a gateway to blockchain database, like:
- GET `/account?address=X`, or
- POST `/transaction/raw`

When developing Semux Light, I have a server which acts as a proxy (and it also combines some queries into one).

I was thinking and also was asked by other developers, if there is a need to create a semux-light-server if:
- the aggregated queries are not that bad to be handled by the frontend,
- if we could remove the API password for some endpoints and just connect to the Semux instance directly and add Cross-Origin Resource Sharing (CORS).

What is your say on this? Maybe some extra configuration parameter? That would let browsers access Semux endpoints directly.

P.S.
One last thing would be to think about some kind of event subscription, but let's not talk about all at once here :)

**Comment by cryptokat** [comment]
As a web developer I'd prefer creating my own proxy server in front of Semux API in order to have a higher degree of control over the availability of endpoints. This can be done easily by Nginx or node.js from my experience.

**Comment by witoldsz** [comment]
@cryptokat that was my initial plan, but then I realized the Semux Light could be not just as a web page with it's backend, but also available as a standalone app:
- download to your pc and launch from your disk,
- wrap as a mobile app

All it would have to do would be (somehow) to find a running Semux instance and connect to it.

It is always less work/trouble for someone just to run and maintain a public Semux instance than to run and maintain both: semux instance and semux-light server.

What do you think?

**Comment by cryptokat** [comment]
@witoldsz That's exactly what [ARK](https://github.com/ArkEcosystem/) is doing which makes light wallet development become much easier. One concern is that the approach might encourage attackers to attempt brute-force attacks on public Semux API servers as the current implementation signs transactions with the private keys inside of wallet.data which ARK doesn't do. Therefore serving public APIs through an independent port other than 5171 would be considered as a safer approach for the purpose of light wallet development.

**Comment by witoldsz** [comment]
Well, I was thinking on making public API with no password and rest would be still hidden behind a password, but you are right, brute forcing public nodes could be dangerous.

As you said: the public API could be served on separate port or the password-protected endpoints could be disabled when public API is on.

There are pros/cons to the approach of making public API at all, it is not a blocker. Just wanted to have a discussion about it.

The alternative would be to setup proxy server (it could disable password for mapped endpoints and add CORS support). That's also an alternative to semux-light-server.

One more option would be to create a standalone Java server which would just embed the Semux within. I was thinking about it as well.

Lots of ways to go, lots of pros and cons to each.

**Comment by orogvany** [comment]
A proxy would be better.  But if you wanted to just host direct you could hack out pass and remove unsafe methods.  But id think youd want ability to cache common calls for performance and other scale type features.

**Comment by orogvany** [comment]
Think we can probably call this discussion good/closed.

Because of our API support for signing from local wallet, users should setup a proxy to ensure correct functionality when exposing to internet at large.

**Comment by witoldsz** [comment]
I am fine with proxy. It's not a big deal. Future versions of Semux Light would probably require more that just a simple proxy anyway.
