### ISSUE TITLE
Unable to set `nonce` for `/transfer`

### ISSUE THREAD

**Issue by semuxdev** [semuxproject/semux#880]
I was trying to send transactions with a partially synced client. All my transactions got rejected, because I was unable to set the nonce for transactions, using the `/transfer` API.  The only way to achieve this is to use `/compose-raw-transaction`, which is not very convenient because it involves two API calls to get the transaction broadcast.

Suggest adding an optional `nonce` field to the existing `/transfer`, `/vote`, `/unvote`, `/delegate` endpoints.

**Comment by cryptokat** [comment]
closed via #883
