### ISSUE TITLE
Weird drop-down menu height

### ISSUE THREAD

**Issue by semuxdev** [semuxproject/semux#882]
#### System information

Semux version: `v1.2.0`

OS & Version: `Windows 10`

Commit hash : `9a32c30cadd9f5147a526b548ff365c58f4cfe0c`

![capture](https://user-images.githubusercontent.com/35751971/40317757-651b0f48-5cf0-11e8-93f5-f960167cdb07.PNG)

**Comment by cryptokat** [comment]
related to https://github.com/semuxproject/semux/commit/539c79c392b8b6949393c6444761f20b2af53201

**Comment by cryptokat** [comment]
closed via #889
