### ISSUE TITLE
Consider reverting 'Rank only updates once per 200 blocks'

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux#894]
After using the new develop feature where rank is only updated once per 200 blocks

it's a little confusing to users.  If a validator drops below spot 100 they wont know until it's too late, as it will still show their old position.

We've added the 'consensus' panel that shows forging order now, so the need for this feature has been replaced/honored by the new info panel.

**Comment by cryptokat** [comment]
How about marking the validators which are going to be kicked out in the next round with yellow background? As #816 explained, it can be really confusing for new users that some of the top-100 delegates are not validators with the original sorting method. Also there will be no way to get the internal position of a validator from GUI if reverted.

**Comment by orogvany** [comment]
Not sure why internal position would matter apart from information provided by concensus tab.  With roundrobin, should be all equal.

Hm, it's a little confusing both ways.  Yes, a yellow background would help.  I've just been finding myself forcing sort to by votes, and then trying to infer position that way, which gets annoying.

Not sure right answer here, both have their pros/cons

**Comment by cryptokat** [comment]
The internal position can be useful for estimating one validator's next forging time as the consensus info table only shows the current validator and the next.

**Comment by orogvany** [comment]
Maybe so.  I just find it fairly confusing to use at the moment, but I could just be used to the previous implementation.

Right now, ordering updates if you're >100, but as soon as you get to spot 101, you stop updating position.  This feels inconsistent.

**Comment by orogvany** [comment]
superseded by #899
