### ISSUE TITLE
NPE on API block-by-number

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux#898]
http://localhost:5171/v2.0.0/block-by-number?number=2

expected: block

actual:
`{"success":false,"message":"Failed to process your request: null"}`

It occurs in getCoinbaseTransaction()

**Comment by cryptokat** [comment]
Unable to reproduce locally. Could the cause be corrupted database?

**Comment by orogvany** [comment]
It's a database that was updated via the 1.1.0 DB update, rather than a fresh sync.
I see that for recent transactions it works.

What mechanism populated the coinbasetransaction hashses during 1.1.0 db update?

**Comment by cryptokat** [comment]
Still unable to reproduce with an upgraded database from 1.0

**Comment by orogvany** [comment]
Attempting to force DB update again in case development DB was upgraded prior to your change and post DB migration initial commit.

Probably the issue.

**Comment by orogvany** [comment]
Ok, that resolved it. closing.

Sorry for false alarm.
