### ISSUE TITLE
Validators get to forge consecutive block

### ISSUE THREAD

**Issue by mdodong** [semuxproject/semux#90]
Validators get to forge consecutive block if the previous validator missed its change to validate. We can add some kind check to see if a the same validator already mined the last block to prevent this. 
```
if minedLastBlock==True:
    skipValidator
```

![screenshot from 2017-10-19 06-03-34](https://user-images.githubusercontent.com/9822458/31745198-4a4aaee4-b494-11e7-85b5-90898dde6a6c.jpg)

**Comment by semuxproject** [comment]
Adding the condition check is not enough. For instance:

block 1, primary = A; however, A is not online, so it goes to B; and B is not online, so it goes to *C*.
block 2, primary = B; B back online, so it goes to B;
block 3, primary = *C*;

In this case, C forges two blocks in 100 blocks.

**Comment by mdodong** [comment]
Having to forge 2 blocks in 100 blocks is okay just not consecutive blocks. This will give incentive to having a stable validator.

**Comment by clip123** [comment]
also if statement: if #of validators are less than 2 then consecutive block forging is allowed.
