### ISSUE TITLE
http://api.semux.org/ is forcing version 1.2.0 instead of >= 1.1.0 without notice.

### ISSUE THREAD

**Issue by Michail1** [semuxproject/semux#913]
Semux client 1.1.1 closed down last night requiring an upgrade to 1.2.0.

http://api.semux.org/version    was changed to force this upgrade.
- {"minVersion":"1.2.0","latestVersion":"1.2.0"}

Forcing all users to upgrade to 1.2.0 should be given time and/or scheduled instead of an immediate upgrade without notice.

**Comment by semuxdev** [comment]
The version 1.1.0 will stop working in one month due to issue #799. However, we reverted the min version change.

**Comment by orogvany** [comment]
Its sufficient that for next month users will receive notice to update.  With enough notice they at least know why it stopped working when #799 rears its ugly head.  But thanks. Closing as fixed

**Comment by orogvany** [comment]
"minVersion":"1.1.0","latestVersion":"1.2.0"}
