### ISSUE TITLE
Possible memory issue

### ISSUE THREAD

**Issue by GMule2k** [semuxproject/semux#94]
I am running Beta4, on Win10 x64, with x64 Java build 1.8.0_144-b01.  I am running the wallet as a validator and over time I see the memory used increasing.  I restarted the wallet (memory used was 1gb, over 12 hours memory back to 734.8mb).  I know Java has a garbage collector to try and stop leaks, but I assume it's not meant to increase over time?

System restarted
Restart +15hr mem usage for Wallet at (KB Commit, Working Set, Shareable, Private) 933896, 746740, 21500, 723700
Restart +24hr:30min mem usage up to respective vals: 1056236, 807992, 22312, 748348

**Comment by semuxproject** [comment]
For validator, memory usage up to 4GB is expected, especially when the network is flooded with transactions.
